cli/main.go
**What I did**
Sorted the imports in the CLI's main.go.
=> Sort main imports

ecs/awsResources.go, ecs/backend.go, ecs/cloudformation.go, ecs/cloudformation_test.go, ecs/compatibility.go, ecs/convert.go, ecs/ec2.go, ecs/ps.go, ecs/sdk.go, ecs/testdata/simple/simple-cloudformation-conversion.golden, ecs/up.go, ecs/volumes.go, ecs/x.go
**What I did**
Refactored and cleanup ECS conversion code for better readability and maintainability
/test-ecs
=> ECS conversion code cleanup and refactoring

cli/cmd/run/run.go, cli/cmd/run/run_test.go, cli/cmd/run/testdata/run-help.golden, cli/cmd/run/testdata/runtest1.env, cli/cmd/run/testdata/runtest2.env, cli/options/run/opts.go
**What I did**
Add `envFile` arguments to run command
Resolves https://github.com/docker/compose-cli/issues/365
=> Add envFile arguments to run command

ecs/volumes.go
Closes https://github.com/docker/compose-cli/issues/685
=> Normalize volume names

tests/aci-e2e/e2e-aci_test.go, tests/framework/e2e.go
We were getting 500 errors because database is not ready initially
**What I did**
* do not only retry GET on errors, also retry if status is not the expected one.
https://github.com/docker/compose-cli/runs/1193172850
/test-aci
=> ACI tests : Wait for http status and retry if necessary. 

tests/aci-e2e/e2e-aci_test.go
**What I did**
Run tests in random regions, listed from error message when trying non available regions
https://github.com/docker/compose-cli/issues/682
/test-aci
=> Running tests in many regions to avoid per region limit when we run too many // things in the CI

ecs/volumes.go
PR https://github.com/docker/compose-cli/pull/717 didn't fix the issue.
This should fix it (I tested it)
Closes https://github.com/docker/compose-cli/issues/685
=> Normalize volume name

api/compose/api.go, cli/cmd/compose/list.go, ecs/list.go, ecs/ps.go, ecs/sdk.go, ecs/wait.go
Detect image pull failures on task creation.
```
$ docker compose up
[+] Running 10/10
⠿ hello                                                                                                                                177.0s
⠿ CloudMap                                                                                                                             174.0s
⠿ HelloTaskExecutionRole                                                                                                                 132.0s
⠿ HelloDefaultNetwork                                                                                                                  127.0s
⠿ Cluster                                                                                                                              128.0s …
```
=> Detect task failures during deployment 

ecs/awsResources.go
**What I did**
Don't set security groups for NLBs
/test-ecs
=> NLB don't support securityGroups

aci/volumes.go, tests/aci-e2e/e2e-aci_test.go
**What I did**
This checks the volume mounts of all container groups from all
resource groups before removing a volume/fileshare
https://github.com/docker/compose-cli/issues/733
**Tests**
/test-aci
=> Look for all mounts before removing a volume

aci/convert/convert.go
**What I did**
Remove the `inline` option for the secrets
https://github.com/docker/compose-cli/issues/663
**Tests**
/test-aci
=> Remove inline secrets option

aci/convert/convert.go, docs/aci-compose-features.md, tests/aci-e2e/e2e-aci_test.go, tests/composefiles/aci_secrets/Dockerfile, tests/composefiles/aci_secrets/compose-invalid-target.yml, tests/composefiles/aci_secrets/compose.yml, tests/composefiles/aci_secrets/my_secret1.txt, tests/composefiles/aci_secrets/my_secret2.txt
**What I did**
Squash all secrets in a single one
Also adds an e2e test
https://github.com/docker/compose-cli/issues/663
**Tests**
/test-aci
=> Squash all secrets in a single one

cli/cmd/volume/command.go, cli/main.go, ecs/aws.go, ecs/awsResources.go, ecs/aws_mock.go, ecs/backend.go, ecs/cloudformation_test.go, ecs/sdk.go, ecs/volumes.go
**What I did**
implement VolumeService on ECS/EFS and removed ACI-only restriction on `volume` commands 
https://github.com/docker/compose-cli/issues/742
=> CLI command to manage ECS volumes

docs/aci-compose-features.md
**What I did**
Fix secrets docs on mounts
Resolves https://github.com/docker/compose-cli/issues/807
/test-aci
=> Fix secrets docs on mounts

cli/cmd/run/run.go, cli/options/run/opts.go
**What I did**
Add --rm to run command (as not yet implemented)
Resolves https://github.com/docker/compose-cli/issues/801
=> Add --rm to run command (as not yet implemented)

ecs/awsResources.go
**What I did**
Fixing empty vpcId that prevented custom VPCs to work
fixes #851
=> Fixing empty vpcId that prevented custom VPCs to work

ecs/sdk.go
**What I did**
Implement pagination on DescribeSubnets API call
Maybe https://github.com/docker/compose-cli/issues/864 is related
/test-ecs
=> DescribeSubnets uses pagination

tests/composefiles/aci_secrets_resources/compose.yml, tests/composefiles/aci_secrets_resources/web/Dockerfile, tests/composefiles/aci_secrets_resources/web/main.go
**What I did**
* Reduced test image size by rewriting in Go
=> Replace Python test image with Go binary

ecs/sdk.go
**What I did**
Add detection of changeset creation failure when compose model has no change vs deployed one
closes #875
/test-ecs
=> Detect changeset creation failure when there's no change

api/containers/api.go, local/backend.go, local/backend_test.go, local/containers.go, local/convert.go, local/convert_test.go, local/e2e/backend_test.go, local/volumes.go
**What I did**
* Set env vars on run
* Set restart policy on run
* Set memory/CPU limits on run
* Improved inspect
* Add rudimentary volume support
* Add command support
=> Local backend improvements

ecs/cloudformation.go, ecs/compatibility.go
**What I did**
Detect use of bind mounts which are not supported on Fargate
https://github.com/docker/compose-cli/issues/894
https://github.com/docker/compose-cli/issues/891
/test-ecs
=> Don't panic on bind mount

cli/cmd/inspect.go, cli/cmd/testdata/inspect-out-id.golden, tests/aci-e2e/e2e-aci_test.go, tests/e2e/testdata/inspect-id.golden, tests/framework/e2e.go
**What I did**
Add container inspect view
/test-aci
=> Add container inspect view

protos/compose/v1/compose.proto
**What I did**
https://github.com/docker/node-sdk/pull/53#discussion_r525230435
=> Fix tabs vs spaces

local/dependencies.go
**What I did**
enforce we only process once by using a unicity set while walking the dependency graph
=> Fix processing dependency graph only onces per node

local/compose.go, local/convergence.go, local/dependencies.go
**What I did**
Use a dependency graph to start services
The algorithm is like so:
* get all the leaves of the graph, these are all the service that don't have any dependency
* once a service is started we take the list of its parents (dependents)
* if all the dependencies of each of those dependents are started then we can start it as well
* if not then we continue to the next dependent
Tested on 
```yaml
services:
db:
build: db
image: gtardif/sentences-db
words:
build: words
image: gtardif/sentences-api
ports:
- "8080:8080"
web:
build: web
image: gtardif/sentences-web
ports:
- "80:80"
```
And 
```yaml
services:
db:
build: db
image: gtardif/sentences-db
words:
build: words
image: gtardif/sentences-api
ports:
- "8080:8080"
depends_on:
- db
web:
build: web
image: gtardif/sentences-web …
```
=> Use a dependency graph to start services

aci/aci.go, aci/compose.go, aci/convert/volume.go, aci/convert/volume_test.go, aci/volumes.go, tests/aci-e2e/e2e-aci_test.go
**What I did**
Add auto creation of fileshares
Resolves https://github.com/docker/compose-cli/issues/830 https://github.com/docker/compose-cli/issues/841
**Tests**
/test-aci
=> Add auto creation of fileshares

local/compose.go
It contains the same output that `docker pull` shows
=> Use json progress message

local/dependencies.go
**What I did**
Fix some linter issues when running `make lint`
=> Fix some linter issues when running `make lint`

Makefile
**What I did**
Update `make pre-commit` with more checks
=> Update `make pre-commit` with more checks

local/backend.go, local/build.go, local/compose.go, local/convergence.go, local/labels.go
**What I did**
Use labels for volumes created by `docker compose` to align with doker-compose
https://github.com/docker/compose-cli/issues/964
=> Volume labels

aci/aci.go, aci/volumes.go, ecs/down.go, ecs/wait.go, local/compose.go, local/convergence.go, progress/event.go, progress/writer.go
**What I did**
* allow one-liner to sent progress events
* more homogeneous events for creating, created, ...
* display error status in case of errors
/test-aci
/test-ecs
=> Refactor progress events

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/build.go, cli/cmd/compose/compose.go, ecs/local/compose.go, ecs/up.go, example/backend.go, local/compose.go
**What I did**
Introduce `compose build` command - local only
=> introduce `compose build` command

cli/cmd/compose/up.go, local/compose.go, local/dependencies.go, local/dependencies_test.go, local/labels.go, progress/event.go
**What I did**
Add order to down command
Resolves https://github.com/docker/compose-cli/issues/938
/test-aci
/test-windows
**Dependencies**
https://github.com/docker/compose-cli/issues/965 on the 'com.docker.compose.project.config_files' label implementation
=> Add order to down command

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/compose.go, cli/cmd/compose/pull.go, ecs/local/compose.go, ecs/up.go, example/backend.go, local/compose.go, progress/event.go, progress/tty.go, progress/tty_test.go
**What I did**
Implemented `docker compose pull`
Fixes #930 
=> Implement `docker compose pull`

local/dependencies.go
(example : awesome-compose ELK stack)
**What I did**
* Removed hardcoded status and init status from up or down differently
* fixed down on awesome-compose ELK stack
https://github.com/docker/compose-cli/issues/1004
=> Fix service initial status in graph, in order to fix compose down duplicate removal of container

local/e2e/compose_test.go
**What I did**
* don't count networks, check network name in network list, based on project name
=> Remove flakyness in compose e2e test : can’t count networks as we have several compose stacks start in //

Dockerfile, Makefile
**What I did**
Added a containerized `go mod tidy`. Sometimes outputs differ depending on your platform ¯\_(ツ)_/¯
=> Containerize go mod tidy

tests/compose-e2e/compose_test.go, tests/compose-e2e/fixtures/simple-composefile/docker-compose.yml
**What I did**
Added test for compose pull
=> Add test for compose pull

cli/main.go
**What I did**
populate `version` opt and redirect to docker/cli if set
https://github.com/docker/compose-cli/issues/1049
=> Parse --version and forward to docker/cli

ecs/awsResources.go, ecs/cloudformation_test.go
**What I did**
Make x-aws-vpc usage more flexible by detecting use or ARN instead of a vpc ID.
Will avoid more confusion, as custom extension usage, without validation (see https://github.com/compose-spec/compose-go/issues/66), is already error prone
Reported on community slack
/test-ecs
=> Support user passing an ARN for x-aws-vpc

MAINTAINERS
**What I did**
Fixed my name :)
=> Fix typo in MAINTAINERS

.github/workflows/ci.yml
**What I did**
Bumped the linter used by the CI to match what we have in the Dockerfile.
=> Bump linter on CI

Dockerfile
**What I did**
Bumped Golang to 1.15.6
=> Bump Golang to 1.15.6

api/compose/api.go, cli/cmd/compose/compose.go, cli/cmd/compose/convert.go, cli/cmd/compose/down.go, cli/cmd/compose/list.go, cli/cmd/compose/logs.go, cli/cmd/compose/run.go, cli/cmd/compose/up.go, local/compose/run.go, server/proxy/compose.go
**What I did**
This separates project name and service name for command `run`
=> Refactor ProjectName

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/run.go, cli/cmd/compose/up.go, ecs/local/compose.go, ecs/up.go, example/backend.go, local/compose/containers.go, local/compose/convergence.go, local/compose/create.go, local/compose/down.go
**What I did**
introduce --remove-orphans option
detect cotnainers which claim to be part of the project but we don't have a matching service in project model
warn user or remove them
https://github.com/docker/compose-cli/issues/1070
/test-aci
/test-ecs
/test-windows
=> introduce --remove-orphans option

ecs/sdk.go
**What I did**
Handle pagination on AWS API which return NextToken
Didn't include the few API call where we pass an explicit ID
close #1104
/test-ecs
=> handle API pagination

.github/workflows/aci-tests.yml, .github/workflows/ci.yml, .github/workflows/ecs-tests.yml, .github/workflows/release.yaml, .github/workflows/windows-ci.yml
**What I did**
Setup the docker cli on GHA
**Tests**
/test-windows
/test-aci
/test ecs
Resolves #1063
=> Setup docker cli on gha

ecs/sdk.go
**What I did**
Use uuid to produce a unique s3 bucket name for (temporary) storage of cloudformation template
https://github.com/docker/compose-cli/issues/1077
/test-ecs
=> s3 bucket name must be unique. Create bucket with uuid name

cli/cmd/compose/compose.go, cli/cmd/compose/convert.go, cli/cmd/compose/up.go, go.mod, go.sum
**What I did**
Introduce `--env-file` option to let user select an alternate .env file
fixes #1152
=> Introduce --env-file

cli/cmd/context/create_kube.go, kube/charts/charts.go, kube/charts/helm/chart.go, kube/charts/helm/helm.go, kube/charts/kubernetes/kube.go, kube/charts/kubernetes/pod.go, kube/charts/kubernetes/volumes.go, kube/compose.go
**What I did**
* Fix compiler / linter errors on kube backend
* Separated from https://github.com/docker/compose-cli/pull/1174 to avoid mixing different issues ; adding kube backend to makefile will be done separately to avoid too many conflicts with #1174 
* because of build tag, kube backend code was not compiled, lint nor tested in CI
=> Fixing Kube compile / lint errors

aci/compose.go, api/client/compose.go, api/compose/api.go, api/progress/event.go, cli/cmd/compose/up.go, ecs/local/compose.go, ecs/up.go, local/compose/create.go, local/compose/down.go, local/compose/stop.go
**What I did**
`Stop` project on Ctrl+C instead of `Down`
=> Stop project on Ctrl+C

aci/e2e/e2e-aci_test.go
**What I did**
* when container is stuck in "ContainerGroupTransitioning", waiting for 3 secs does not help, just removed the container and recreate it for next steps to continue
https://github.com/docker/compose-cli/pull/1178/checks?check_run_id=1778321097#step:7:224
And several similar examples previously hit
/test-aci
=> Better resolution for ACI flakyness on container stop/restart

local/compose/create.go
Couldn't reproduce https://github.com/docker/compose-cli/issues/1168 but looks like it needs defensive code here.
**What I did**
Add defensive code
Resolves https://github.com/docker/compose-cli/issues/1168
=> Add defensive code

api/compose/api.go, cli/cmd/compose/up.go, local/compose/convergence.go, local/compose/create.go
**What I did**
introduce compose up flags --force-recreate and --no-recreate to align with docker-compose
=> introduce --force-recreate and --no-recreate

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/compose.go, cli/cmd/compose/start.go, cli/cmd/compose/stop.go, cli/cmd/compose/up.go, ecs/local/compose.go, ecs/up.go, kube/compose.go, local/compose/down.go, local/compose/stop.go
**What I did**
Add start and stop commands
Resolves https://github.com/docker/compose-cli/issues/1176
=> Add start and stop commands

local/compose/convergence.go, local/compose/down.go
**What I did**
Use the same name for progress on containers everywhere: prefi with "Container" like we do for Network, Volumes...
=> Make progress event display homogeneous between up, down, start, stop

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/ps.go, cli/server/proxy/compose.go, ecs/local/compose.go, ecs/ps.go, kube/compose.go, local/compose/ps.go
**What I did**
Introduce --all option on compose ps for parity with docker-compose
close https://github.com/docker/compose-cli/issues/1197
=> Introduce --all option on compose ps

cli/cmd/compose/build.go, cli/cmd/compose/compose.go, cli/cmd/compose/compose_test.go, cli/cmd/compose/convert.go, cli/cmd/compose/down.go, cli/cmd/compose/pull.go, cli/cmd/compose/push.go, cli/cmd/compose/start.go, cli/cmd/compose/stop.go, cli/cmd/compose/up.go, go.mod, go.sum, local/compose/attach.go
**What I did**
Added support for --profiles according to compose-spec
=> Introduce --profile option

aci/compose.go, api/client/compose.go, api/compose/api.go, api/progress/event.go, cli/cmd/compose/compose.go, cli/cmd/compose/kill.go, ecs/cloudformation.go, ecs/local/compose.go, kube/compose.go, local/compose/containers.go, local/compose/kill.go
**What I did**
Added `compose kill` command for parity with docker-compose
=> Add kill command

ecs/sdk.go
**What I did**
Fixed a typo and added some user-guidance in error message
https://github.com/docker/compose-cli/issues/1235
=> clearer error message and fix typo

kube/helm/helm.go
**What I did**
Initialize helm action by default with no logger
/test-kube
=> Init helm action by default with no logger, don’t require callers to initialise it.

local/compose/create.go, local/e2e/compose/compose_test.go, local/e2e/compose/fixtures/volume-test/compose.yml
**What I did**
Add configs bind mount read-only support
Resolves https://github.com/docker/compose-cli/issues/937
=> Add configs bind mount support

api/compose/tags.go, cli/cmd/compose/up.go, local/compose/labels.go
**What I did**
Resolves https://github.com/docker/compose-cli/issues/965
=> Add environment_files label on service's `env_file` section

cli/cmd/compose/up.go, cli/cmd/compose/up_test.go
**What I did**
introduced support for --scale
=> add support for up --scale

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/compose.go, cli/cmd/compose/remove.go, ecs/local/compose.go, ecs/run.go, kube/compose.go, local/compose/attach.go, local/compose/compose.go, local/compose/containers.go, local/compose/convergence.go, local/compose/remove.go
**What I did**
Reproduced `docker-compose rm` command and flags
/test-windows
=> introduce compose rm command

local/e2e/compose/cascade_stop_test.go
**What I did**
Add cascade test cleanup with `down`
=> Add cascade test cleanup with `down`

.github/workflows/ci.yml, Makefile
Signed-off-by: Ulysses Souza <ulyssessouza@gmail.com>
=> Use gotestsum to make FAILURES more visible

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/down.go, cli/cmd/compose/remove.go, cli/cmd/compose/stop.go, cli/cmd/compose/up.go, ecs/local/compose.go, ecs/up.go, kube/compose.go, local/compose/create.go, local/compose/down.go, local/compose/down_test.go, local/compose/stop.go, local/compose/stop_test.go
**What I did**
introduce timeout flag on down and stop
https://github.com/docker/compose-cli/issues/1275
=> introduce timeout flag on down and stop

api/progress/plain.go, cli/cmd/compose/build.go, cli/cmd/compose/convert.go, cli/cmd/compose/pull.go
**What I did**
introduce --quiet option
close #1280
=> introduce --quiet option

.github/workflows/aci-tests.yml, .github/workflows/ci.yml, .github/workflows/ecs-tests.yml, .github/workflows/kube-tests.yml, .github/workflows/release.yaml, Dockerfile, builder.Makefile, cli/cmd/compose/down.go, cli/cmd/compose/pull.go, local/compose/down.go
**What I did**
* Docker 20.10.3
* Golang 1.16
* golangci-linter 1.37.0
* Add arm64 builds for macOS and Linux
=> Add Arm builds for macOS and Linux

go.mod, go.sum, local/compose/pull.go, local/compose/push.go
**What I did**
* Replaced references to docker/distribution with distribution/distribution
=> Replace docker/distribution with distribution/distribution

ecs/e2e/ecs/e2e-ecs_test.go
**What I did**
Fixed e2e test on ECS
/test-ecs
=> progress writes to stderr

cli/cmd/compose/create.go, cli/cmd/compose/up.go, local/compose/build.go
**What I did**
Introduced --no-build option to disable building images from source
https://github.com/docker/compose-cli/issues/1291
=> introduce --no-build option

cli/cmd/compose/compose.go, cli/cmd/compose/compose_test.go, go.mod, go.sum, local/compose/convergence.go, local/compose/create.go, local/compose/run.go, local/compose/status.go, local/e2e/compose/fixtures/network-test/compose.yaml
**What I did**
Add service based network_mode
Resolves https://github.com/docker/compose-cli/issues/1011
Depends on https://github.com/compose-spec/compose-go/pull/103
=> Add service based network_mode

cli/cmd/compose/run.go, cli/cmd/compose/up.go
**What I did**
added `--timeout` option to `docker compose up` by overriding `StopGracePeriod` in compose model
added `--no-deps` option to `docker compose up` by marking all dependent services as "disabled"
=> add --timeout option to compose up

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/build.go, ecs/local/compose.go, ecs/up.go, kube/compose.go, local/compose/build.go
**What I did**
support compose build --pull --progress
https://github.com/docker/compose-cli/issues/1359
https://github.com/docker/compose-cli/issues/1358
=> support compose build --pull

api/compose/api.go, cli/cmd/compose/pull.go, cli/cmd/compose/run.go, cli/cmd/compose/up.go, cli/cmd/compose/up_test.go, local/compose/convergence.go, local/compose/create.go
**What I did**
introduce pull --include-deps
disable all dependency services so that they are ignored by Pull
https://github.com/docker/compose-cli/issues/1361
=> introduce pull --include-deps

api/compose/api.go, cli/cmd/compose/up.go, local/compose/attach.go, local/compose/containers.go, local/compose/pause.go, local/compose/remove.go, local/compose/start.go
This actually makes the service selection effective and add the flag to disable the service selection.
=> Add --attach-dependencies

aci/convert/container.go, api/compose/api.go, cli/cmd/compose/build.go, go.mod, go.sum, local/compose/build.go, local/e2e/compose/compose_build_test.go, local/e2e/compose/fixtures/build-test/nginx-build/Dockerfile
**What I did**
introduce --build-args option to compose build 
https://github.com/docker/compose-cli/issues/1360
=> introduce --build-args option

cli/cmd/compose/convert.go, kube/client/client.go, kube/client/utils.go, kube/compose.go, kube/e2e/compose_test.go, kube/resources/kube.go, kube/resources/secrets.go, kube/resources/volumes.go
**What I did**
- added support for secrets
- wait for pods to be in running/terminated state on `compose up/down`
- add timeout 
/test-kube
=> Kube backend updates from Hack days

go.mod, go.sum
**What I did**
Bump `compose-go`
Resolves https://github.com/docker/compose-cli/issues/1261
=> Bump compose-go to fix struct merges

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/compose.go, cli/cmd/compose/top.go, ecs/local/compose.go, ecs/top.go, kube/compose.go, local/compose/top.go, local/e2e/compose/compose_test.go
Implement `compose top`.
```
$ docker compose top
compose-cli_web_1
UID    PID     PPID    C    STIME   TTY   TIME       CMD
root   73864   73803   0    10:24   ?     00:00:00   nginx: master process nginx -g daemon off;   
101    74422   73864   0    10:24   ?     00:00:00   nginx: worker process                        
compose-cli_web_2
UID    PID     PPID    C    STIME   TTY   TIME       CMD
root   73863   73784   0    10:24   ?     00:00:00   nginx: master process nginx -g daemon off;   
101    74230   73863   0    10:24   ?     00:00:00   nginx: worker process                        
compose-cli_web_3
UID    PID     PPID    C    STIME   TTY   TIME       CMD
root   73862   73823   0    10:24   ?     00:00:00   nginx: master process nginx -g daemon off;   
101    74400   73862   0 …
```
=> Add `compose top` command

local/compose/build.go, local/compose/convergence.go, local/compose/pull.go
Resolves https://github.com/docker/compose-cli/issues/1325
=> Take `platform` in account on pulling and building images

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/compose.go, cli/cmd/compose/events.go, cli/formatter/colors.go, cli/formatter/logs.go, ecs/local/compose.go, ecs/up.go, go.mod, kube/compose.go, local/compose/attach.go, local/compose/create.go, local/compose/events.go, local/compose/run.go, local/compose/start.go, local/e2e/compose/compose_test.go, local/e2e/compose/fixtures/attach-restart/compose.yaml
**What I did**
Introduce `compose events` command
https://github.com/docker/compose-cli/issues/1283
we considered this one to be left until requested by user, but I actually need the backend code to implement attaching to containers on restart, so ¯\_(ツ)_/¯
=> introduce docker compose events

api/compose/api.go, cli/cmd/compose/up.go, go.mod, go.sum, local/compose/build.go, local/compose/create.go, local/compose/run.go
**What I did**
Add `quietPull` option to `up`
Resolves https://github.com/docker/compose-cli/issues/1368
Depends on https://github.com/docker/buildx/pull/558
=> Add `quietPull` option to `up`

go.mod, go.sum
=> bump compose-go

local/compose/build.go, local/compose/create.go
**What I did**
Introduce support for more composefile attributes
note: didn't replicated docker/cli parsing for device mapping, better get Parse method made public
https://github.com/docker/compose-cli/issues/1423
=> add support for a few more composefile attributes

aci/compose.go, api/client/compose.go, api/compose/api.go, api/progress/event.go, cli/cmd/compose/compose.go, cli/cmd/compose/restart.go, docs/reference/docker_compose.yaml, docs/reference/docker_compose_restart.yaml, ecs/local/compose.go, ecs/up.go, kube/compose.go, local/compose/convergence.go, local/compose/restart.go, local/compose/status.go, local/e2e/compose/fixtures/restart-test/compose.yml, local/e2e/compose/restart_test.go
Resolves https://github.com/docker/compose-cli/issues/1389
=> Add restart command

cli/cmd/compose/compose.go, cli/cmd/compose/convert.go, go.mod, go.sum
**What I did**
introduce --no-interpolate flag to align with docker-compose
require https://github.com/compose-spec/compose-go/pull/117
=> --no-interpolate

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/pull.go, ecs/local/compose.go, ecs/up.go, kube/compose.go, local/compose/pull.go
**What I did**
Add --ignore-pull-failures to command pull
Resolves https://github.com/docker/compose-cli/issues/1409
=> Add --ignore-pull-failures to command pull

local/compose/down.go, local/compose/down_test.go, local/compose/kill_test.go, local/compose/stop_test.go
**What I did**
Use cached container list on command down
Resolves https://github.com/docker/compose-cli/issues/1304
=> Reuse container list on command down

local/compose/build.go, local/compose/build_win.go
**What I did**
* Use moby shellout to build not only on build command but also on up command
* pull required images 
compose up requiring pull & build: 
``` 
$ ./bin/docker compose -f ..\awesome-compose\aspnet-mssql\docker-compose-hello.yaml up
Sending build context to Docker daemon  2.445MB
Step 1/12 : FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS build
---> e9c6e831319b
Step 2/12 : WORKDIR /app
---> Using cache
---> abbc6033ff83
Step 3/12 : COPY *.sln .
---> Using cache
---> 0ea1919aa542
Step 4/12 : COPY aspnetapp/*.csproj ./aspnetapp/
---> Using cache
---> 9e0205e95a2f
Step 5/12 : RUN dotnet restore
---> Using cache
---> a0ff609dbec5
Step 6/12 : COPY aspnetapp/. ./aspnetapp/
---> Using cache
---> 21758dd6e629
Step 7/12 : …
```
=> Use old build for windows engine also on compose up

cli/cmd/compose/compose.go
**What I did**
add support for COMPOSE_PROFILES as described in reference documentation
https://github.com/docker/compose-cli/issues/1492
=> add support for COMPOSE_PROFILES

cli/mobycli/exec.go
**What I did**
check exit code from dicker-cli shellout and track cancel status in metrics if exitcode == 130
=> Track cancel exit code from docker cli shellout to report correct status in metrics

cli/mobycli/job_windows.go, go.mod
**What I did**
Made windows-specific code simpler
align with https://github.com/docker/pinata/pull/15539
/test-windows
=> make windows "kill children process" code simpler

local/compose/convergence.go, local/e2e/compose/compose_test.go, local/e2e/compose/fixtures/init-container/compose.yaml
**What I did**
introduced support for service_completed_successfully
(aka init container)
close https://github.com/docker/compose-cli/issues/1499
=> add support for service_completed_successfully

cli/cmd/compose/compose.go, cli/cmd/compose/convert.go
Resolves https://github.com/docker/compose-cli/issues/1519
=> Fix compose config --profiles

go.mod, go.sum, local/compose/create.go
**What I did**
Set container limits based on service definition
close https://github.com/docker/compose-cli/issues/1523
=> configure container limits and resources

local/compose/create.go
**What I did**
Ignore mount options that do not apply to the selected mount type
warn user about configuration mismatch
close https://github.com/docker/compose-cli/issues/1524
=> ignore mount options which don't match type

api/compose/api.go, cli/cmd/compose/build.go, cli/metrics/metrics.go, cli/metrics/metrics_test.go, cli/mobycli/exec.go, local/compose/build.go, local/e2e/compose/scan_message_test.go, utils/scan_suggest.go
**What I did**
* Do not print the scan message when the quiet flag is specified
* Print the scan message to stderr instead of stdout
Fixes: #1517 
/test-windows
=> Fix scan message with quiet flag

.github/workflows/ci.yml, Dockerfile, ecs/autoscaling_test.go, ecs/cloudformation_test.go
**What I did**
* Bump linter to 1.39.0
* Use dockerfile:1.2 syntax instead of experimental
* Fix typo in GitHub Actions
=> Bump linter minor Dockerfile and CI fixes

aci/e2e/aci-demo/web/Dockerfile, local/e2e/compose/fixtures/attach-restart/compose.yaml, local/e2e/compose/fixtures/build-test/nginx-build/Dockerfile, local/e2e/compose/fixtures/build-test/nginx-build2/Dockerfile, local/e2e/compose/fixtures/cascade-stop-test/compose.yaml, local/e2e/compose/fixtures/ipc-test/compose.yaml, local/e2e/compose/fixtures/logs-test/compose.yaml, local/e2e/compose/fixtures/network-test/compose.yaml, local/e2e/compose/fixtures/restart-test/compose.yml, local/e2e/compose/fixtures/run-test/compose.yml, local/e2e/compose/fixtures/simple-build-test/nginx-build/Dockerfile, local/e2e/compose/fixtures/simple-composefile/compose.yml, local/e2e/compose/fixtures/start-stop/compose.yml, local/e2e/compose/fixtures/volume-test/nginx-build/Dockerfile, local/e2e/compose/ipc_test.go
**What I did**
* Reduced the number of base images we need for e2e tests
* Rewrote the aci-demo web service Dockerfile
=> E2e test improvements

aci/e2e/aci-demo/web/Dockerfile, local/e2e/compose/fixtures/attach-restart/compose.yaml, local/e2e/compose/fixtures/build-test/nginx-build/Dockerfile, local/e2e/compose/fixtures/build-test/nginx-build2/Dockerfile, local/e2e/compose/fixtures/cascade-stop-test/compose.yaml, local/e2e/compose/fixtures/ipc-test/compose.yaml, local/e2e/compose/fixtures/logs-test/compose.yaml, local/e2e/compose/fixtures/network-test/compose.yaml, local/e2e/compose/fixtures/restart-test/compose.yml, local/e2e/compose/fixtures/run-test/compose.yml, local/e2e/compose/fixtures/simple-build-test/nginx-build/Dockerfile, local/e2e/compose/fixtures/simple-composefile/compose.yml, local/e2e/compose/fixtures/start-stop/compose.yml, local/e2e/compose/fixtures/volume-test/nginx-build/Dockerfile, local/e2e/compose/ipc_test.go
Reverts docker/compose-cli#1533
=> Revert "E2e test improvements"

cli/cmd/compose/compose.go, cli/cmd/compose/version.go
**What I did**
Cherry picked from https://github.com/docker/compose-cli/pull/1397
close https://github.com/docker/dev-tooling-team/issues/299
=> Introduce compose version command

aci/e2e/aci-demo/web/Dockerfile, aci/e2e/aci_secrets_resources/web/Dockerfile, local/e2e/compose/compose_test.go, local/e2e/compose/fixtures/attach-restart/compose.yaml, local/e2e/compose/fixtures/build-test/nginx-build/Dockerfile, local/e2e/compose/fixtures/build-test/nginx-build2/Dockerfile, local/e2e/compose/fixtures/cascade-stop-test/compose.yaml, local/e2e/compose/fixtures/ipc-test/compose.yaml, local/e2e/compose/fixtures/logs-test/compose.yaml, local/e2e/compose/fixtures/network-test/compose.yaml, local/e2e/compose/fixtures/restart-test/compose.yml, local/e2e/compose/fixtures/run-test/compose.yml, local/e2e/compose/fixtures/simple-build-test/nginx-build/Dockerfile, local/e2e/compose/fixtures/simple-composefile/compose.yml, local/e2e/compose/fixtures/start-stop/compose.yml, local/e2e/compose/fixtures/volume-test/nginx-build/Dockerfile, local/e2e/compose/fixtures/wrong-composefile/compose.yml, local/e2e/compose/ipc_test.go, local/e2e/compose/scan_message_test.go, local/e2e/compose/start_stop_test.go, local/e2e/container/container_test.go
**What I did**
* Reduce the number of images we need to pull for the tests
* Cleanup older Dockerfiles
* Fix Compose start/stop tests
/test-windows
=> Local test cleanup

local/compose/create.go
Resolves https://github.com/docker/compose-cli/issues/1568
=> Fix progress writer network creation and removal

api/compose/api.go, cli/cmd/compose/images.go, cli/cmd/compose/remove.go, cli/cmd/compose/stop.go, local/compose/remove.go, local/compose/stop.go
**What I did**
pass user selected services to stop/remove so only those get affected
close https://github.com/docker/compose-cli/issues/1571
close https://github.com/docker/compose-cli/issues/1572
=> only stop/remove selected services

aci/compose.go, api/client/compose.go, api/compose/api.go, api/compose/delegator.go, api/compose/noimpl.go, cli/cmd/compose/exec.go, ecs/exec.go, ecs/local/compose.go, kube/compose.go, local/compose/exec.go, local/e2e/compose/compose_exec_test.go
**What I did**
Inspect exec after completion to return exitcode on `docker compose exec`
close https://github.com/docker/compose-cli/issues/1607
=> docker compose exec to return command exit code

local/compose/create.go, local/compose/down.go, local/compose/down_test.go, local/e2e/compose/volumes_test.go
**What I did**
implement "down --volumes" to cleanup compose application named volumes
close https://github.com/docker/compose-cli/issues/1553
=> down --volume to remove volume

docs/ecs-compose-examples.md, docs/ecs-compose-features.md
fixes: https://github.com/docker/compose-cli/issues/1631
fixes some documentation that doesn't work as expected.
=> fix documentation errors

api/compose/api.go, cli/cmd/compose/ps.go, local/compose/ps.go
**What I did**
Added support for services with `ps` command
Resolves https://github.com/docker/compose-cli/issues/1547
=> Add support for services on ps command

local/compose/convergence.go
**What I did**
Setup container(s) with ip address as defined by service's network config
close https://github.com/docker/compose-cli/issues/1582
=> configure service with ipAddress

local/compose/create.go
**What I did**
Applied "single" ulimit as both hard and soft
close https://github.com/docker/compose-cli/issues/1638
https://docker.atlassian.net/browse/IL-135
=> apply single ulimit as soft+hard limit

docs/reference/docker_compose.yaml, docs/reference/docker_compose_build.yaml, docs/reference/docker_compose_convert.yaml, docs/reference/docker_compose_images.yaml, docs/reference/docker_compose_port.yaml, docs/reference/docker_compose_pull.yaml, docs/reference/docker_compose_rm.yaml
**What I did**
`make -f builder.Makefile yamldocs`
=> Update compose docs

api/compose/api.go, api/compose/api_test.go, local/compose/run.go
**What I did**
Support bypass envvars
Resolves https://github.com/docker/compose-cli/issues/1560
=> Support bypass envvars

local/compose/exec.go
**What I did**
Configure `exec` environment by merging service env as defined in compose file and --env parameters, and resolve values using project's environment.
close https://github.com/docker/compose-cli/issues/1681
=> define exec env by merging service env with command line --env

cli/cmd/compose/compose.go, go.mod, go.sum
**What I did**
based on https://github.com/compose-spec/compose-go/pull/140
close docker/compose-cli#1668
=> support compose file set by COMPOSE_FILE env var

README.md
Signed-off-by: Lorena Rangel <lorena.rangel@docker.com>
**What I did**
=> Fix readme: remove extra single quotes

go.mod, go.sum
**What I did**
updated compose-go dependency to get https://github.com/compose-spec/compose-go/pull/141
close https://github.com/docker/compose-cli/issues/1701
=> update compose-go dependency

api/progress/writer.go, cli/cmd/compose/build.go, cli/cmd/compose/down.go, cli/cmd/compose/pause.go, cli/cmd/compose/pull.go, cli/cmd/compose/push.go, cli/cmd/compose/remove.go, cli/cmd/compose/restart.go, cli/cmd/compose/run.go, cli/cmd/compose/start.go, cli/cmd/compose/stop.go, cli/cmd/compose/up.go, cli/cmd/run/run.go, cli/cmd/volume/command.go
**What I did**
Only a limited set of `progress.Run` usages do return a value. 
This PR introduce RunWithStatus to cover the few others, to make most common code simpler
=> code cleanup: most progress.Run don't return a value

go.mod, go.sum
- diff: https://github.com/docker/docker/compare/v20.10.5...v20.10.7
- diff: https://github.com/docker/cli/compare/v20.10.6...v20.10.7
=> go.mod: update docker and cli to v20.10.7

local/compose/pull.go
**What I did**
UX fix: only report pull progress if we have images to pull, skip otherwise
=> only report pull progress if we have something to pull

kube/client/client.go, kube/client/utils.go, kube/compose.go, kube/helm/helm.go, kube/resources/kube.go
Several improvements in the kubernetes backend:
- pod status check on `compose up/down/ps`
- compose project update on `compose up`
- port mapping  for LB services in `compose ps`
- implement `docker compose exec` command
/test-kube
=> Kube backend updates

cli/cmd/compose/build.go, cli/cmd/compose/exec.go, cli/cmd/compose/run.go, docs/reference/compose_build.md, docs/reference/compose_port.md, docs/reference/compose_ps.md, docs/reference/compose_restart.md, docs/reference/compose_run.md, docs/reference/compose_top.md, docs/reference/docker_compose.yaml, docs/reference/docker_compose_build.yaml, docs/reference/docker_compose_cp.yaml, docs/reference/docker_compose_exec.yaml, docs/reference/docker_compose_port.yaml, docs/reference/docker_compose_ps.yaml, docs/reference/docker_compose_run.yaml, docs/reference/docker_compose_top.yaml
**What I did**
Updated reference documentation and generated yamldocs to be included on docs.docker.com
https://docker.atlassian.net/browse/IL-133
=> update reference docs

.github/workflows/cli-release.yaml, .github/workflows/plugin-release.yaml
**What I did**
release process to include binary distribution LICENSE
=> include packaging LICENSE in release

local/compose/create.go, local/e2e/compose/fixtures/network-alias/compose.yaml
**What I did**
Fixed regression on network aliasses test
=> fix broken network_alias_test

local/compose/create.go
**What I did**
Avoids conflict when volumes are declared on same path but some use a trailing `/` by normalizing mount target using `path.Clean`
Also fix inherited volume computation (`ImageInspect.ContainerConfig` is not set with Dockerfile VOLUME, we have to use `ImageInspect.Config`)
close https://github.com/docker/compose-cli/issues/1775
=> fix volume inheritance and conflict with trailing '/'

local/e2e/compose/fixtures/network-alias/compose.yaml, local/e2e/compose/networks_test.go, pkg/compose/convergence.go
Signed-off-by: Lorena Rangel <lorena.rangel@docker.com>
**What I did**
Set links and external link in the container when connected to the network. 
closes #1634
=> Set container links

cli/mobycli/exec.go
**What I did**
If `com.docker.cli` is not in the path, look for it next to the current running executable.
Fixes #754
To test:
1. with Docker Desktop installed make sure to move `com.docker.cli` out of the path by doing e.g. `mv /Applications/Docker.app/Contents/Resources/bin/com.docker.cli /Applications/Docker.app/Contents/Resources/bin/com.docker.cli_`
2. build and run `./bin/docker version`, it should error out with
```
$ ./bin/docker version
exec: "com.docker.cli": executable file not found in $PATH
Current PATH : (…)
```
3. copy `com.docker.cli` into `./bin`:
```
cp /Applications/Docker.app/Contents/Resources/bin/com.docker.cli_ ./bin/com.docker.cli
```
4. re-run:
```
$ ./bin/docker version
Client:
Cloud integration: 2.0.0-beta.4-1-g949062d5
Version: …
```
=> IL-250 Look for docker cli next to the current executable

cmd/compose/ps.go, local/e2e/compose/compose_test.go, local/e2e/compose/restart_test.go, local/e2e/compose/start_stop_test.go, pkg/api/api.go, pkg/compose/ps.go
**What I did**
Added COMMAND column to `compose ps` to align with `docker ps`
=> compose ps to include container command

local/e2e/compose/volumes_test.go, pkg/compose/create.go
**What I did**
Inherit anonymous volume from previous container
includes test case
close https://github.com/docker/compose-cli/issues/1815
=> inherit anoymous volumes

cmd/compose/remove.go
**What I did**
pass --force and --volumes options to backend
close https://github.com/docker/compose-cli/issues/1844
=> pass --force and --volumes options to backend

README.md
**What I did**
I noted that some statements in the README.md were outdated, minor updates. 
You might want to do still more with the confusion about being v1 here but v2 in docker-compose
=> Minor readme.md issues (no more docker desktop stable/edge, etc.)

.github/ISSUE_TEMPLATE.md
**What I did**
Just added docker-compose version to issue template.
=> Issue template should ask for docker-compose version

cmd/compose/ps.go
**What I did**
`compose ps` to return error when no container has been found for requested service.
close https://github.com/docker/compose-cli/issues/1893
=> report error on `ps` when no container found for service(s)

kube/compose.go, pkg/api/proxy.go, pkg/compose/logs.go, pkg/compose/start.go
**What I did**
Detect new containers on `logs --follow`.
Fixes https://github.com/docker/compose-cli/issues/1635
=> Detect new containers on logs --follow

cmd/compose/ps.go
**What I did**
apply filter before formatter is selected
close https://github.com/docker/compose-cli/issues/1993
=> apply filter before formatter

pkg/compose/create.go
**What I did**
Consider `volume_from` as an implicit definition for service dependencies
close https://github.com/docker/compose-cli/issues/2035
=> include volume_from as a source for implicit dependencies

pkg/compose/pull.go
Add a warning when trying to pull an image that should be built
**What I did**
Resolves https://github.com/docker/compose-cli/issues/2016
=> Add build warning on pull

.github/workflows/artifacts.yml, .github/workflows/pending_answered.yml, .github/workflows/pr-closed.yml
**What I did**
Build cross platform binaries and publish artifacts as part of PR builds to make it easier testing changes
=> publish cross platform artifacts for PRs

cmd/compose/build.go, pkg/api/api.go, pkg/compose/build.go
close https://github.com/docker/compose-cli/issues/2027
=> Only build requested services

docs/aci-container-features.md
Signed-off-by: Usha Mandya <usha.mandya@docker.com>
**What I did**
Fixed a typo
https://github.com/docker/docker.github.io/issues/13824
=> Fix a typo

go.mod, go.sum
**What I did**
Bumped compose to v2.2.0 and compose-go to v1.0.5
=> Bump compose to v2.2.0 and compose-go to v1.0.5

cli/metrics/commands.go
**What I did**
Added "sbom" to the list of management commands for metrics (for https://github.com/docker/sbom-cli-plugin)
N/A
^ so grumpy, yet, still cute
=> Add SBOM management command

cli/metrics/conn_other.go
**What I did**
DD relies on having the CLI socket available in /var/run when running in
WSL. So in case we can't find the CLI socket in the calling user's home
directory, fall back to /var/run.
=> Fall back to global CLI socket on Linux

cli/cmd/context/rm.go, cli/cmd/context/use.go, local/e2e/cli-only/e2e_test.go
**What I did**
fix warnings on 'docker context use'
Fixes https://github.com/docker/cli/issues/3765
=> cli: fix warnings on 'docker context use'

cli/metrics/commands.go, cli/metrics/docker_command.go, cli/metrics/docker_command_test.go
* for per-invocation events, only look at Compose `alpha` commands
* for aggregated events, include Compose `alpha` commands
=> metrics: adjust Compose event collection

cli/mobycli/scout_suggest.go
The `docker scout quickview` hint, displayed after a user pulls or builds an image, only works if the user is logged in to Hub.
**What I did**
Check if user is logged in, and make hint more explicit/call this requirement out if not.
Logged in (same behaviour as before):
Logged out (add message about logging in):
=> scout hint: tell user logging in is required
