docker/compose-cli

api/client/client.go, server/interceptor.go, server/metrics.go, server/metrics_test.go, server/proxy/proxy.go, server/server.go
**What I did**
* never fail in metrics interceptor
* send context type, not context name
=> Api metrics context: send context type, not contet name, and never fail

.github/workflows/ci.yml
**What I did**
Update workflow to run on PRs, and only on main branch (if on all branches, for every PR that would run one GH Action for the branch push on the fork, and one for the PR opening)
Seen in #683 : build happens on push on forks, but the build notifications are not propagted to the PR
=> Update CI workflow to build fine on PRs from forks

.github/labeler.yml
**What I did**
Add *api* label to PRs touching to /protos
noticed #640 did't get this label where I would have expected it
=> Label PRs touching to protos

docs/aci-interation.md
**What I did**
Add ACI integration doc
https://github.com/docker/compose-cli/issues/253
=> ACI integration doc, listing main feature mapping and noticeable differences between local docker experience and ACI deployment.

cli/main.go, metrics/metrics.go, metrics/metrics_test.go, tests/e2e/e2e_test.go
**What I did**
* Use metrics GetCommand() that is already used 3 lines above.
* added e2e local test and unit test for this specific case in metrics.GetCommand() (that already worked as expected)
=> Do not fail when constructing error message for commands not implemented, if command flags are not recognized.

tests/aci-e2e/e2e-aci_test.go
**What I did**
* changed order of parameters in e2e invocation
https://github.com/docker/compose-cli/runs/1192523711, container logs show explicit error while ACI is trying to restart container in a loop : `starting container process caused "exec: \"--domainname\": executable file not found in $PATH"`
/test-aci
=> Fix ACI e2e : now we support passing commands, set `--domainname` before the image in the cmd

Makefile
**What I did**
Add pre-commit target to Makefile to make it more practical to run all the things in the minimal checklist before committing/pushing.
=> Add pre-commit target to Makefile

cli/cmd/login/login.go, tests/e2e/e2e_test.go
**What I did**
* Removed login arg check since `azure` is now a subcommand and not a code path in the `login` command. 
https://github.com/docker/compose-cli/issues/712
/test-aci
/test-windows
=> Fix regression: let users login to local registry (no ‘.’ In registry name)

ecs/architecture.md, ecs/autoscaling.go, ecs/autoscaling_test.go, ecs/awsResources.go, ecs/cloudformation.go, ecs/iam.go, ecs/testdata/simple/simple-cloudformation-conversion.golden, ecs/x.go
**What I did**
Introduced `x-aws-autoscaling` and configure autoscaling policy with a CPU percent target
https://github.com/docker/compose-cli/issues/668
/test-ecs
=> Introduce x-aws-autoscale to support CPU based autoscaling

aci/convert/registry_credentials.go, aci/login/helper.go, aci/login/login.go
See `az cloud list` to list endpoints specific to each azure cloud.
See #658 
**What I did**
* regroup & de-duplicate azure constants
=> Regroup azure constants that might be things to switch in order to provide access to other azure clouds

ecs/aws.go, ecs/down.go, ecs/sdk.go, ecs/wait.go
**What I did**
this is a workaround for CloudFormation issue to manage CapacityProvider <-> Cluster reverse dependency
`compose down` on ECS first delete the CapacityProvider and AutoscalingGroup (if present) by imperative API call then run `DeleteStack`. This prevent Cluster deletion by CloudFormation to fail
https://github.com/docker/docker_aws/issues/43
/test-ecs
=> delete CapacityProvider before we invoke DeleteStack

cli/cmd/context/create.go, cli/cmd/context/rm.go, cli/main.go, docs/cli/orig/context_create.md
Signed-off-by: Amos Law <ahlaw.dev@gmail.com>
**What I did**
Normalize case of command help messages and add recursive function to override help flags.
Fixes [#597](https://github.com/docker/compose-cli/issues/597)
=> Normalize case of command and flag help

tests/e2e/testdata/ls-out-json-windows.golden
**What I did**
Added the windows correspondent golden file for `context ls`
You can add a / mention to run tests executed by default only on main branch : 
/test-aci
/test-windows
=> Add windows golden file for `context ls`

tests/aci-e2e/e2e-aci_test.go
to be put reverted once the platform is back to green (hopefully in a day or 2)
**What I did**
* limit test runnnig to eastus2 for now
* do not fail on `docker exec test-container pwd` error
* do not deploy mysql
https://github.com/docker/compose-cli/pull/727/checks?check_run_id=1211239383#step:6:101
/test-aci
=> Temporarily disable some red ACI tests

ecs/wait.go
**What I did**
Prior to #706 progress message included `DELETE_COMPLETE` and e2e test is based on this string found on output.
/test-ecs
=> restore status in addition to reason as progress message

cli/cmd/context/ls.go, cli/cmd/version.go, formatter/consts.go, tests/e2e/e2e_test.go
**What I did**
* `docker context ls` reads format `{{json.}}`as `json` 
=> Allow `docker context ls —formatter {{json.}}` to not delegate to Moby and include context type in the json

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/compose.go, cli/cmd/compose/up.go, ecs/local/compose.go, ecs/up.go, example/backend.go
Added a `detach` flag to the up api method that returns after stack creation if flag is set.
```
$ docker compose up -d
$ docker compose ls
NAME                STATUS
hello               Starting
$ docker compose ls
NAME                STATUS
hello               Running
```
/test-ecs
Closes https://github.com/docker/compose-cli/issues/666
=> Add detach flag to `compose up`

docs/aci-compose-features.md
**What I did**
Document ACI support for compose fields
https://github.com/docker/compose-cli/issues/253
=> Compose to ACI mapping documentation

Makefile
**What I did**
Add ACI E2E resource cleanup command in makefile
=> Add ACI E2E resource cleanup command

tests/aci-e2e/e2e-aci_test.go, tests/framework/e2e.go
**What I did**
Fix `e2e-aci` tests on comparing with empty string.
It's not that the old code is not "correct", but the comparison wasn't getting to the right assertion. When printing the value just before or comparing the empty string, that went back to work.
I'm not sure what happened here, maybe that's a GO specifics that I ignore. Anyways, IMHO comparing with empty string even looks more readable.
**Tests**
/test-aci
=> Fix e2e-aci tests on comparing with empty string

aci/login/client.go, builder.Makefile, cli/cmd/version.go, cli/main.go, ecs/sdk.go, internal/variables.go
**What I did**
Add version to UserAgent on  ACI
This also refactors the Version insertion to make it global
Resolves https://github.com/docker/compose-cli/issues/619
=> Add version to UserAgent on  ACI

tests/aci-e2e/e2e-aci_test.go
**What I did**
Trim line return to fix tests on windows
https://github.com/docker/compose-cli/runs/1242211704
/test-windows
/test-aci
=> Trim line returns for windows tests

aci/backend.go, cli/cmd/compose/compose.go, cli/cmd/compose/list.go, cli/cmd/compose/ps.go, cli/cmd/secrets.go, cli/cmd/volume/list.go, tests/aci-e2e/e2e-aci_test.go
**What I did**
Add `--quiet` for some commands
- compose ls
- compose ps
- secret ls
- volume ls
**Tests**
/test-aci
Resolves https://github.com/docker/compose-cli/issues/745
=> Add --quiet for some commands

tests/aci-e2e/e2e-aci_test.go
**What I did**
Add DB log info when DB cannot start 
https://github.com/docker/compose-cli/runs/1246145363
/test-windows
=> Add debug information when mysql cannot start on ACI E2E test

tests/aci-e2e/e2e-aci_test.go
**What I did**
This deployment is too flaky, still associated with new logs from the Atlas platform
https://github.com/docker/compose-cli/runs/1246970427
=> Disabling mysql ACI test again, see https://github.com/docker/compose-cli/runs/1246970427

aci/containers.go
ACI SDK returns status 200 but nil container group properties
**What I did**
Check for empty container ID, and never dereference nil pointer
/test-aci
=> Fix panic when invoking inspect with empty container id 

.github/workflows/ci.yml, go.mod, go.sum
**What I did**
* remove x/sys indirect dep causing darwin error, `go mod tidy` (I don't understand where this dep came from in the first place)
* Added cross compile step in CI build
https://github.com/docker/compose-cli/runs/1248196250
=> Remove indirect dependency causing error on Darwin build. Adding cross compile in CI build (all PRs)

ecs/awsResources.go, ecs/cloudformation.go, ecs/cloudformation_test.go, ecs/compatibility.go
**What I did**
Allow user to pass EFS volume options by `driver_opts` in volume configuration
Move volume creation into cloudformation template with `Retain` policy so it survives `down`, reports on console as `DELETE_SKIPPED`
fixes #781
/test-ecs
=> Let user pass EFS create option by driver_opts

aci/backend.go, aci/convert/convert.go, aci/resources.go, api/client/client.go, api/client/resources.go, api/resources/api.go, backend/backend.go, cli/cmd/prune.go, cli/main.go, ecs/backend.go, ecs/local/backend.go, example/backend.go, local/backend.go, server/metrics_test.go, tests/aci-e2e/e2e-aci_test.go
**What I did**
* Add ResourceService() interface next to ContainerService, ComposeService, to hold Prune() that is not specific to any kind of resource
* Add a cli `prune` command, with `--dry-run` and `--force`flags
* Add an ACI implementation, deleting containers and compose apps, Running ones only if `--force`
Many things still subject to discussion/improvement: 
* exact ouput needs to be refined (probably remove `deleted resources:` before IDs ; I'm more and more thinking output should be driven by the backend, to possibly provide custom info like amount of CPU saved, maybe money saved, etc.)
* we could display a summary or freed resources : nb CPU, memory 
* there is no gRPC API yet
* ECS implementation should be easy to add …
=> ACI docker prune

tests/aci-e2e/e2e-aci_test.go
(errors on `docker exec`: failed to read input from container: ws closed: 1000, cf https://github.com/docker/compose-cli/runs/1247798295)
**What I did**
* keep check on output containing "/" but allow `docker exec` to exit with error
https://github.com/docker/compose-cli/runs/1247798295
/test-aci
=> Make one ACI test less strict, we still encounter issues related to deployments on Atlas platform

.github/workflows/ci.yml
**What I did**
* Check CI exec timing and decided to keep full cross compile, rather than specifically compile for  darwin, since the  overall exec time will not be that different
* document why we have this step in CI
=> Document cross build step reason & timing in CI

aci/convert/convert.go, aci/resources.go, api/client/resources.go, api/resources/api.go, cli/cmd/prune.go, tests/aci-e2e/e2e-aci_test.go
**What I did**
* Add summary after list of deleted resources: 
```
$ ./bin/docker --context acicontext prune --dry-run --force
Resources that would be deleted:
test-prune1
test-prune2
Total CPUs reclaimed: 5.02, total memory reclaimed: 5.40 GB
```
https://github.com/docker/compose-cli/issues/744
/test-aci
=> Display summary of reclaimed ACI resources (CPU/mem) in `docker prune`

docs/examples.md
Added some simple examples of compose files for ECS.
Closes https://github.com/docker/compose-cli/issues/784
=> Add compose file examples for ECS

cli/cmd/context/create_ecs.go, ecs/backend.go, ecs/context.go, tests/ecs-e2e/e2e-ecs_test.go
When creating an ECS context we set profile, region and AWS credentials. Credentials are saved under the profile section in .aws/credentials while the region is saved under the profile section in .aws/config.
This fixes:
- creation of new profiles -- region and/or credentials must be provided
- enables the use of the default profile -- the 'Profile' field is not added to the ECS context.
- remove access id and secret key parameters for context create
```
$ rm ~/.aws/config ~/.aws/credentials
```
```
$ docker context create ecs test1 --description "Test default profile"
? Select AWS Profile new profile
? profile name default
? Enter AWS credentials No
? Region eu-west-3
Successfully created ecs context "test1"
```
```
$ cat ~/.aws/config
[default]
region = eu-west-3
```
```
$ cat …
```
=> Populate ~/.aws/config(credentials) on ecs context create

ecs/awsResources.go, ecs/cloudformation.go, ecs/cloudformation_test.go, ecs/sdk.go
**What I did**
1. add a sanity check to sdk.DescribeService
2. store external cluster as template metadata so we can get this information back
DescribeService API, even we pass a service ARN, require cluster ID (?)
If cluster was set by user as `x-aws-cluster`, we can't get this ID from CloudFormation stack resources
Proposed change uses CloudFormation template Metadata to track the user-provided cluster so we can easily get this ID back on `compose ps`
https://github.com/docker/compose-cli/issues/790
/test-ecs
=> Store external cluster as metadata

aci/convert/convert.go, aci/convert/convert_test.go
as these paths are container side, not cli side. (do not work with windows paths)
Signed-off-by: guillaume.tardif <guillaume.tardif@gmail.com>
**What I did**
Replace `import filepath` by `import path` ; `path` works with "/" as file separate and is not os sensitive
https://github.com/docker/compose-cli/runs/1264272389
/test-windows
=> Fix unit tests on windows: for secret target path, use path.Join etc. instead of filepath.Join

ecs/compatibility.go, ecs/down.go
**What I did**
Claim support for `services.ulimits` - conversion was actually already implemented
According to ECS docs, fargate only allows use of `nofile` ulimit, so the custom CompatibilityChecker
fix https://github.com/docker/compose-cli/issues/664
/test-ecs
=> add support for ulimits.nofile

Makefile
=> Fix Makefile command to cleanup ACI E2E resource groups

ecs/architecture.md
Fixing x-aws-autoscaling typo in architecture document
=> fix "autoscaling" typo

api/secrets/api.go, cli/cmd/secrets.go, ecs/sdk.go, tests/ecs-e2e/e2e-ecs_test.go
Add password file argument to secret create
```
$ echo "secretpassword" | docker secret create test -
arn:aws:secretsmanager:eu-west-3:175142243308:secret:test-vDMzik
```
```
$ docker secret create test pass.txt
arn:aws:secretsmanager:eu-west-3:175142243308:secret:test-Ue0s6C
```
```
$ docker secret create test -
?  *************************************
arn:aws:secretsmanager:eu-west-3:175142243308:secret:test-Hru0Qu
```
Closes https://github.com/docker/compose-cli/issues/678
/test-ecs
=> Add password file argument to secret create (handles '-' as stdin read)

ecs/backend.go, ecs/cloudformation_test.go, ecs/compatibility.go, ecs/ec2.go, ecs/ec2_test.go
**What I did**
User can select custom AMI and machine type to configure CapacityProvider by setting `node.ami` and `node.machine` placement constraints
https://github.com/docker/compose-cli/issues/661
=> Allow user to set ami/machine by Deploy.Placement.Constraint

ecs/autoscaling.go, ecs/aws.go, ecs/awsResources.go, ecs/aws_mock.go, ecs/backend.go, ecs/cloudformation.go, ecs/cloudformation_test.go, ecs/convert.go, ecs/ec2.go, ecs/iam.go, ecs/sdk.go, ecs/testdata/simple/simple-cloudformation-conversion.golden, ecs/volumes.go
**What I did**
Generate an [AccessPoint](https://aws.amazon.com/fr/s3/features/access-points/) for compose file's volumes so that binding can be customized:
- add support for `uid`,`gid` to let container access a volume without entering the file permission hell
- add support for `root_directory` so volume can actually point to a sub-path within the filesystem
- add support for creating such a sub-path for uid,gid + permissions
How to test:
Create a compose file to create filesystem as root: 
```yaml
services:
server:
image: jenkins/jenkins:lts
user: root
volumes:
- config:/var/jenkins_home
volumes:
config: {}
```
Then update compose file to remove the root user and double check filesystem still can be mounted read/writen by container without posix permission issues
```yaml
services: …
```
=> Introduce use of EFS Access Point to mount filesystems as volumes

ecs/wait.go, progress/tty.go
On errors, the event status text exceeds one line length and this breaks the progress writer output. 
We now removed the status truncation from wait and calculate the max length for the status text based on the terminal width in the progress writer.
At the end, we return the full error text.
```
$ docker compose up
[+] Running 10/10
⠿ hello                       DELETE_COMPLETE                                                                                          192.0s
⠿ Cluster                     DELETE_COMPLETE                                                                                          142.0s
⠿ DefaultNetwork              DELETE_COMPLETE                                                                                          142.0s
⠿ CloudMap …
```
=> Remove status truncate on wait

aci/volumes.go, cli/cmd/volume/command.go
**What I did**
This passes the pointer to the concrete `struct` instead of a copy
/test-aci
=> Fix volume create cli bug

ecs/autoscaling.go, ecs/autoscaling_test.go, ecs/cloudformation.go
**What I did**
Introduce a struct to support autoscaling parameters on x-aws-autoscaling
https://github.com/docker/compose-cli/issues/767
=> Configure autoscaling parameters

ecs/awsResources.go
Cross zone load balancing is enabled by default for NLB.
```
version: "3.8"
services:
hello:
image: ancaiordache/hello
ports:
- 8080:8080
```
```
docker compose up
[+] Running 14/14
⠿ hello                       CREATE_COMPLETE                                                                                          217.0s
⠿ LogGroup                    CREATE_COMPLETE                                                                                            2.0s
⠿ Cluster                     CREATE_COMPLETE                                                                                            5.0s
⠿ DefaultNetwork              CREATE_COMPLETE                                                                                            5.0s
⠿ HelloTCP8080TargetGroup     CREATE_COMPLETE …
```
=> Enable cross zone load balancing

formatter/formatter.go, formatter/formatter_test.go, tests/e2e/testdata/ls-out-json-windows.golden, tests/e2e/testdata/ls-out-json.golden, tests/e2e/testdata/ps-out-example-json.golden
Print json arrays for 'ps' or 'ls' commands.
```
$ docker ps --format json
[{"ID":"nginx_app","Image":"nginx","Status":"Running","Command":"","Ports":["52.157.252.16:80->80/tcp"]}]
$ docker volume ls --format json
[]
docker compose ls --format json
[{"Name":"e2eTestCompose1602770221964365386","Status":"Running"},{"Name":"e2eTestCompose1601985767794954638","Status":"Running"},{"Name":"e2eTestCompose1601985581055863340","Status":"Running"}]
```
/test-aci
/test-ecs
=> Return json array for  `ps/ls --format json` commands

progress/writer.go
**What I did**
Fixed a typo in comments against Event struct definition inside writer.go
=> Fix typo in comments against Event struct definition inside writer.go

docs/aci-compose-features.md
**What I did**
Fix: *relative* paths are not supported in secret targets
#807 
=> Small fixes in secrets docs

ecs/resolv/Dockerfile, ecs/secrets/Dockerfile
introduced by https://github.com/docker/compose-cli/pull/799
**What I did**
https://hub.docker.com/repository/registry-1.docker.io/docker/ecs-searchdomain-sidecar/builds/4c35d039-2c00-485f-a24a-b5e02a99e39f
=> Fix Dockerfile syntax in ecs sidecars 

prompt/prompt.go
Signed-off-by: Sarath Kumar Sivan <sarathkumarsivan@gmail.com>
**What I did**
Fix typo in comments against Password method attached to User struct defined inside prompt.go
=> Fix typo in comments against Password method attached to User struct

tests/framework/e2e.go
**What I did**
* 🤦 
* Do not multiply timeout by `time.seconds` twice
* add a log when we try GET to make things easier to follow in e2e tests
We were still experiencing e2e not doing retry because the first attempt did not timeout: https://github.com/docker/compose-cli/runs/1313631290
/test-aci
/test-windows
=> Fix e2e GET timeout, was *1000 twice

cli/cmd/context/context.go, cli/cmd/context/update.go, tests/e2e/e2e_test.go
**What I did**
* Fix regression: cannot run command `context update` anymore
https://github.com/docker/compose-cli/issues/811
=> Add update command for backward compatibility

ecs/cloudformation.go, ecs/testdata/simple/simple-cloudformation-conversion.golden
**What I did**
Updated the generated ingress description and the related test case
A platy**o**s.
=> cloudformation: fix typo in generated ingress description

Makefile, aci/convert/convert.go
**What I did**
* pined ACI sidecar image
* updated Makefile: new target to publish new versions, ensuring we don’t override an existing image tag
Will need something similar fo ECS sidecars ; I'd like to add more E2E tests on ECS to be sure not to break anything, will do in a separate PR
/test-aci
=> Pin version of ACI sidecar image, so that we don’t affect prod users when re-publishing :latest.

cli/main.go, cli/main_test.go, tests/aci-e2e/e2e-aci_test.go
**What I did**
* windows PATH should use windows separator (;)
* do not add separator if initial PATH is empty (was creating PATH=:/path)
Maybe fixing https://github.com/docker/compose-cli/issues/754, but not fixing the Konvoy scenario
/test-aci
/test-windows
=> Fix path appending

cli/cmd/context/ls.go, cli/cmd/version.go, formatter/consts.go, formatter/formatter.go, formatter/formatter_test.go, tests/e2e/e2e_test.go, tests/e2e/testdata/ls-out-json-windows.golden, tests/e2e/testdata/ls-out-json.golden, tests/e2e/testdata/ls-out-legacy-json-windows.golden, tests/e2e/testdata/ls-out-legacy-json.golden
this is used by VSCode Docker extension
VSCode should move to using `docker context ls --format json` and parse a regular json array. But for existing deployment, and not introduce breaking changes, `docker context ls —format "{{ json . }}"` will return json lines as before
**What I did**
* Support old format with a specific case, returning json lines and not a full json array; only in the case of the legacy `docker context ls —format "{{ json . }}"` (space variations allowed in the format value)
https://github.com/microsoft/vscode-docker/issues/2452
=> Revert breaking change on `docker context ls —format “{{ json . }}` 

Makefile, ecs/convert.go, ecs/testdata/simple/simple-cloudformation-conversion.golden
**What I did**
* pin  docker/ecs-searchdomain-sidecar:1.0
* Add targets to makefile for publishing new tags
* pushed  docker/ecs-searchdomain-sidecar:1.0
ECS E2E tests not validate cross container communication with https://github.com/docker/compose-cli/pull/849
/test-ecs
=> Pinned and publish docker/ecs-searchdomain-sidecar:1.0

README.md
**What I did**
* Update main readme mission statement to mention Compose applications
* remove Beta warning
* add ACI example on CI deployments
https://github.com/docker/compose-cli/issues/809
=> Update main readme mission statement to mention Compose applications & remove beta warning

Makefile
**What I did**
* Display resource groups that are going to be cleaned up
* grep ignore case, sometimes we have case difference in test resource group names
=> Nicer cleanup make target for ACI resources

ecs/down.go, ecs/wait.go, ecs/wait_test.go, go.mod, go.sum, tests/ecs-e2e/e2e-ecs_test.go
**What I did**
* toCamelCase(ecsStatus). 
* did not change global status display in progress because we are displaying status and reason from ECS. 
display examples: 
```
[+] Running 8/14
⠹ demo-multi-port          CreateInProgress User Initiated                           16.3s
⠹ CloudMap                 CreateInProgress Resource creation Initiated         12.2s
⠿ Cluster                  CreateComplete                                                             5.0s
[+] Running 3/7
⠇ demo-multi-port        DeleteInProgress User Initiated                    15.9s
⠇ DbService              DeleteInProgress                                                14.9s
⠿ DefaultNetworkIngress  DeleteComplete …
```
=> Display ecs status in CamelCase in order to have homogeneous output between backends.

ecs/convert.go
Sorting env pair array to avoid creating different CloudFormation templates between calls
**What I did**
Sorted ENV key value array before marshal so that two consecutive "convert" with the same input docker-compose.yml contents generates the same template contents.
A random ordering was taking place before because ENV is read from a map, which doesn't guarantee key ordering.
This was tested against ECS and it was verified that TaskDefinitions/Task recreations only occur when ENVs are really changed. See below:
Before changing one ENV
After changing one ENV from service "admin-backend"
Verify that version increment occured only to "admin-backend". Before this all services were updated.
#858
**(not mandatory) A picture of a cute animal, if possible in relation with what …
=> Sorting env pair array to avoid creating different CloudFormation templates between calls

Makefile, ecs/convert.go
**What I did**
* pin docker/ecs-secrets-sidecar:1.0 in ecs/convert.go
* check ECS E2E test fail, image not found
* add target to ublish image in makefile, and publish tag 1.0
/test-ecs
=> Pin ECS secrets sidecar image & add makefile targets

cli/cmd/context/ls.go, tests/e2e/e2e_test.go
This had been kept for VSCode extension but is not used, `docker context ls --format “{{ json . }}”` is used in the extension.
**What I did**
* remove hiddent obsolete flag
* double check in VSCode extension nothing is broken
=> Remove obsolete flag `docker context ls --json` (that was marked hidden)

cli/cmd/context/create_ecs.go
**What I did**
Introduce `--access-keys` flag on `context create ecs` command to import an AWS access key CSV file (which isn't actually CSV but key=value pairs file ¯\\_(ツ)_/¯
=> Flag to import access key & secret from file

api/containers/api.go, cli/cmd/run/run.go, cli/cmd/run/testdata/run-help.golden, cli/options/run/opts.go, cli/options/run/opts_test.go
**What I did**
Remap restart policies for command run
This adds 'no' and 'always' as options.
Resolves https://github.com/docker/compose-cli/issues/877
**Tests**
/test-aci
=> Remap restart policies for command run

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/convert.go, ecs/cloudformation.go, ecs/cloudformation_test.go, ecs/local/compose.go, ecs/marshall.go, ecs/testdata/simple/simple-cloudformation-conversion.golden, ecs/up.go, example/backend.go
**What I did**
Allow CloudFormation template to be marshalled as yaml or json. yaml is made the default output format (minor breaking change). Introduced `--format` flag (already used in few other places) to select format. 
This makes template output more concise (8977 vs 13608 bytes for my basic test) when used as AWS API payload.
will reduce the impact of https://github.com/docker/compose-cli/issues/665
/test-ecs
=> Marshall cloudformation template as yaml

tests/ecs-e2e/e2e-ecs_test.go
**What I did**
E2E timeout 3 mins => 4mins , waiting for name resolution between containers
https://github.com/docker/compose-cli/runs/1363717278
/test-ecs
=> ECS E2E timeout update due to flakiness in CI

api/containers/api.go, cli/options/run/opts.go
**What I did**
Move const specific to run command where it's used
=> Minor refactoring: Move list of run specific flags where it’s used

aci/aci.go
Hit this when following logs of a container restarted with a health check: 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x168771e]
goroutine 1 [running]:
github.com/docker/compose-cli/aci.getACIContainerLogs(0x2d85260, 0xc000526c60, 0xc0001465a0, 0x24, 0xc0004f4da0, 0xa, 0xc0004f4db0, 0x7, 0x7ffeefbffab2, 0xb, ...)
github.com/docker/compose-cli/aci/aci.go:285 +0x1fe
github.com/docker/compose-cli/aci.streamLogs(0x2d85260, 0xc000526c60, 0xc0001465a0, 0x24, 0xc0004f4da0, 0xa, 0xc0004f4db0, 0x7, 0x7ffeefbffab2, 0xb, ...)
github.com/docker/compose-cli/aci/aci.go:297 +0x2e5
```
**What I did**
**(not mandatory) A picture of a …
=> Avoid nil pointer when reading logs of a just terminated container.

ecs/aws.go, ecs/aws_mock.go, ecs/sdk.go, ecs/up.go, go.mod, go.sum
**What I did**
As API is limited in size we can't pass large cloudformation template as payload.
This workaround uses a `com.docker.compose` s3 bucket to store the template under random unique ID for the duration of the API call.
close #665
/test-ecs
=> publish Cloudformation template on s3

docs/ecs-compose-features.md
**What I did**
Document ECS support for compose attributes as suggested by https://github.com/docker/compose-cli/issues/839
=> Document ECS supported compose attributes

aci/convert/convert.go, aci/convert/volume.go, aci/convert/volume_test.go
**What I did**
add specific error message when user tries to specify a host path in compose file
https://github.com/docker/compose-cli/issues/865
/test-aci
=> Specific error message when specifying path as a volume source

ecs/convert.go
**What I did**
Accept `reservations` to define Fargate instance size if `limits` is not set.
As Fargate only allow dedicated resource allocation (or, at least, doesn't expose the implementation details about sharing resources) we can't really distinguish those.
/test-ecs
=> Use reservations if user has not set limits

tests/aci-e2e/e2e-aci_test.go, tests/composefiles/aci_secrets_resources/compose.yml, tests/composefiles/aci_secrets_resources/web/Dockerfile, tests/composefiles/aci_secrets_resources/web/main.go
**What I did**
* Add e2e test validating AcI healthchecks
/test-aci
=> Deploy e2e compose stack with health check and validate it restarts failed container

aci/aci.go, aci/compose.go, aci/containers.go, aci/volumes.go
that might lead to nil pointer panic
**What I did**
is in the title
/test-aci
=> Use ACI .IsHttpStatus() rather than accessing .StatusCode directly

metrics/commands.go, metrics/generatecommands/main.go, metrics/metrics.go, metrics/metrics_test.go, tests/e2e/e2e_test.go
**What I did**
Add --help in specific flags we catch in metrics
https://docker.slack.com/archives/C0111G2RCE4/p1605266835109100
=> Collect metrics --help flag

ecs/context.go
**What I did**
Fix ECS context creation by secret+token to override existing .aws/credentials file
https://github.com/docker/compose-cli/issues/910
/test-ecs
=> Don't mess with exiting .aws/credentials

ecs/cloudformation_test.go, ecs/compatibility.go, ecs/convert.go, go.mod, go.sum
**What I did**
In addition to swarm-style for generic_resources, support devices reservation as defined by Adopt https://github.com/compose-spec/compose-spec/pull/100
/test-ecs
=> Add support for gpu devices reservation

docs/ecs-compose-examples.md
**What I did**
I have added IAM roles/policies related examples and re-worked some of the text. For example I re-ordered the `networks` section to be right below the `volumes` and changed the size of other sections / sub-sections to what I thought made more sense. Please have a look if it makes sense for you. 
I found the IAM policy example on the [doc page](https://docs.docker.com/engine/context/ecs-integration/) generated a malformed CFN errors so I created a new example here.
=> Added IAM roles/policies examples and re-ordered some of the text

ecs/local/compose.go
**What I did**
marshall compose enhanced model to docker-compose in json to workaround format mismatch with un-quoted strings.
close https://github.com/docker/compose-cli/issues/914
=> Use json to marshall ecs-local enhanced docker-compose config

aci/convert/convert.go, aci/convert/convert_test.go, cli/cmd/run/run.go, cli/cmd/run/testdata/run-help.golden, cli/options/run/opts.go, cli/options/run/opts_test.go, docs/aci-container-features.md
**What I did**
* Fix healthcheck run params
* do not set successThreshold, from MSFT, this is set to 1 by default and cannot be changed for liveness probe, see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#probe-v1-core
healthcheck deployment sometimes fail 
/test-aci
=> Aci healthcheck threshold

.github/labeler.yml, Dockerfile, Makefile, builder.Makefile, local/backend.go, local/compose.go, local/convergence.go, local/dependencies.go, local/dependencies_test.go, local/labels.go, local/util.go, metrics/conn_e2e.go
**What I did**
* change make target to lint including local & e2e (behind build flag)
* fmt, goimport, fix linter issues
=> Lint local backend

local/compose.go, local/compose_test.go, local/convergence.go, local/labels.go
**What I did**
Add implementation for compose ls
=> Local compose ls implementation

local/compose.go, local/compose_test.go
**What I did**
* swear about manipulating collections in go
* transform a collection of containers to a collection of service status with many for loops
* unit test
=> compose ps implementation

local/compose.go, local/convergence.go, local/convert.go, local/dependencies.go, local/dependencies_test.go, local/util.go
**What I did**
sort services in respect to dependency order so as we recreate one we can flag it's dependent services as `force_recreate` before convergence is applied on those.
Also fix a panic with attempt to write to `results` channel while already closed. Replaced by a dedicated errors channel. 
Bonus: implement `service_healthy` depends_on condition for parity with docker-compose
can be tested using:
```yaml
services:
jenkins:
image: jenkins/jenkins:lts
healthcheck: 
test: "curl http://localhost:8080/login"
redis:
image: redis
depends_on:
jenkins:
condition: service_healthy
```
`compose up` will demonstrate jenkins service being created, and redis one only created after a delay (healthy state)
then change jenkins service configuration, `compose up` will recreate jenkins service …
=> Run convergence in service dependency order

local/e2e/compose_test.go
**What I did**
* e2e test creating local context, `compose up` on our usual compose app with 3 containers, curl localhost:80, `compose ps` and `compose down`. 
=> First local compose e2e tests

docs/aci-compose-features.md
**What I did**
Fix typos in `docs/aci-compose-features.md`:
symetrical -> symmetrical
resoure -> resource
=> Fix typos in `docs/aci-compose-features.md`

.github/workflows/optional-ci.yml
ACI currently has some flaky issue where deploying a payload containing docker credentials just freezes forever without error message
**What I did**
* in windows GHActions workflow, `docker logout` before running ACI E2E tests
https://github.com/docker/compose-cli/pull/952/checks?check_run_id=1442133013
/test-aci
/test-windows
=> On GH Actions windows nodes, ensure there is no automatic docker login before running ACI E2E tests

aci/aci.go, aci/backend.go, aci/containers.go, aci/convert/convert.go, aci/convert/convert_test.go, aci/convert/ports.go, aci/convert/ports_test.go, aci/convert/restartpolicy.go, aci/convert/restartpolicy_test.go, aci/convert/secrets.go, aci/convert/volume.go, aci/convert/volume_test.go, aci/login/client.go, aci/resources.go, aci/volumes.go, cli/cmd/prune.go, go.mod, go.sum
**What I did**
Bump `azure-sdk-for-go`: v43.3.0 -> v48.2.0
Resolves https://github.com/docker/compose-cli/issues/954
/test-aci
/test-windows
=> Bump `azure-sdk-for-go`: v43.3.0 -> v48.2.0

local/compose.go, local/labels.go
**What I did**
* Add container labels version, oneoff, workingDir, configfiles
=> Add container labels to improve compatibility with docker-compose

progress/tty.go
**What I did**
* avoid fiddling with string at negative char index
```
panic: runtime error: slice bounds out of range [:-44]
goroutine 37 [running]:
github.com/docker/compose-cli/progress.lineText(0xc0002d5ea0, 0xc, 0x0, 0x0, 0x0, 0x3173ac7, 0x6, 0xbfe7c1c84e943168, 0x34418a0, 0x4025c20, ...)
/Users/gtardif/docker/src/github.com/docker/compose-cli/progress/tty.go:155 +0x974
github.com/docker/compose-cli/progress.(*ttyWriter).print(0xc0004561e0)
/Users/gtardif/docker/src/github.com/docker/compose-cli/progress/tty.go:127 +0xd65
```
=> Avoid panic in some weird cases (debug in VSCode for example)

local/compose.go, local/e2e/compose_test.go, local/labels.go
**What I did**
* Add 3 compose labels for networks created by compose
* Add tests for compose runtime labels 
https://github.com/docker/compose-cli/issues/963
=> Add compose labels for network

go.mod, go.sum, local/compose.go, local/e2e/compose_test.go
**What I did**
* Use new field in project struct to set label value with composefiles
https://github.com/docker/compose-cli/issues/965
=> Add compose labels for composefiles

go.mod, go.sum
**What I did**
* bump go mod compose-go & go mod tidy
https://github.com/docker/compose-cli/issues/971
=> Latest compose-go, keeping “-“ in project names derived from workingDir

local/compose.go
Will also avoid mixing build output and compose-cli progress display
Signed-off-by: Guillame Tardif <guillaume.tardif@gmail.com>
**What I did**
* Move call to ensureImagesExist() as fist step in compose up
* did **not** fix display issue: 
```
$ ./bin/docker --context localctx compose up -f tests/composefiles/demo_multi_port.yaml
[+] Running 0/0
[+] Running 3/3"    Create                                                                                                                                         0.0s
⠿ Service "web"    Created                                                                                                                                        1.0s
⠿ Service "words"  Created …
```
=> Ensure images are pulled/build with build first, before creating networks / volumes.

local/build.go
**What I did**
Skip build() execution if there's nothing to build
Otherwise progress writer get confused with some `[+] Running 0/0` and breaks
fix https://github.com/docker/compose-cli/issues/977
=> Don't start buildx' build with empty opts

local/compose.go, local/e2e/compose_test.go, tests/aci-e2e/e2e-aci_test.go, tests/framework/e2e.go
**What I did**
* remove compose networks on compose down
https://github.com/docker/compose-cli/issues/967
=> Remove project network on compose down

cli/cmd/compose/compose.go, cli/cmd/compose/compose_test.go, cli/cmd/compose/up.go
**What I did**
`up` can get a subset of compose services to run as arg.
for this purpose, the compose app model is "filtered" to remove all unrelated services, so that the implementation code doesn't have to handle this.
*(not mandatory) A picture of a cute animal, if possible in relation with what you did**
=> filter compose project to remove all services not required by command

local/compose.go, local/convergence.go
**What I did**
* Detect when external network are not available when doing `docker compose up`
* Avid duplicate prefixing of network name with `myproject_`
https://github.com/docker/compose-cli/issues/975
https://github.com/docker/compose-cli/issues/990
=> Compose network error

cli/cmd/compose/build.go, local/e2e/compose_test.go
**What I did**
* Add flags taken from compose up: --file, --workdir
* Add build step in compose e2e tests
https://github.com/docker/compose-cli/issues/997
=> Add compose build flags for file and working dir

local/build.go
`project_service`, like docker-compose.
See awesome_compose/react-express-mongodb example
**What I did**
* set image name as docker-compose
* test `compose_up` on awsome_compose (modified, had to remove node_modues volumes from compose files to skip other issue with volumes)
=> If compose file has a build section and no image name, build image with the right derived image tag

local/compose.go
same as Services, Networks, homogeneous with `compose up`
**What I did**
```
$ ./bin/docker --context localctx compose up -f tests/composefiles/demo_multi_port.yaml
[+] Running 4/4
⠿ Network "composefiles_default"  Created
⠿ Service "db"                    Created
⠿ Service "words"                 Created
⠿ Service "web"                   Created
$ ./bin/docker --context localctx compose down -f tests/composefiles/demo_multi_port.yaml
[+] Running 4/4
⠿ Container composefiles_words_1  Removed
⠿ Container composefiles_web_1    Removed
⠿ Container composefiles_db_1     Removed
⠿ Network "composefiles_default"  Removed
```
=> In `compose down` progress display: prefix container names with “Container”,

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/up.go, ecs/local/compose.go, ecs/up.go, example/backend.go, formatter/logs.go, local/compose.go, local/container.go, local/containers.go, local/convergence.go, local/e2e/compose_test.go, local/labels.go, progress/event.go, server/proxy/compose.go
**What I did**
`up` do (re)create containers, then attach (or collect logs for running ones) and eventually start.
Doing so we reproduce docker-compose behaviour
also handle SIGTERM to run `down`
https://github.com/docker/compose-cli/issues/970
=> Attach to container on `up` and pipe logs to stdout

local/build.go
**What I did**
Fixed ctrl+c on build
The build and progress can't share the same context, the progress context
needs to live longer for the progress to be able to read all the messages
from build.
Fixes #992 
=> Give progress its own context

local/compose.go, local/compose_test.go, local/e2e/compose_test.go, local/e2e/volume-test/docker-compose.yml, local/e2e/volume-test/static/index.html
**What I did**
* avoid double appending of working dir when setting up volumes, instead resolve absolute path if required
* Added unit test & first compose volume e2e test
Fixes https://github.com/docker/compose-cli/issues/1007
=> Compose fix relative volume

local/build.go, local/compose.go, local/e2e/compose_test.go, local/e2e/volume-test/docker-compose.yml, local/e2e/volume-test/nginx-build/Dockerfile
**What I did**
* Correctly tag compose image during `compose up` build phase, if service has no image  section
* Add this in existing E2E test case
https://docker.slack.com/archives/C0111G2RCE4/p1607098325467700
=> Fix compose up build when no image name in compose file

local/compose.go
**What I did**
List containers with `all` option so we also remove the stopped ones.
https://github.com/docker/compose-cli/issues/993
=> Remove stopped containers on `down`

.github/workflows/ci.yml, Makefile, api/client/client.go, cli/cmd/compose/build.go, cli/cmd/compose/compose.go, cli/cmd/compose/convert.go, cli/cmd/compose/down.go, cli/cmd/compose/list.go, cli/cmd/compose/logs.go, cli/cmd/compose/ps.go, cli/cmd/compose/pull.go, cli/cmd/compose/push.go, cli/cmd/compose/up.go, local/backend.go, local/build.go, local/compose.go, local/compose_test.go, local/container.go, local/containers.go, local/convergence.go, local/convert.go, local/convert_test.go, local/dependencies.go, local/dependencies_test.go, local/e2e/compose_test.go, local/labels.go, local/util.go, local/volumes.go, tests/e2e/e2e_test.go
**What I did**
* in compose command, do not warn command is not available on default context type, rather use "local" backend when on "moby" context type.
* change e2e tests to not require a local context.
* local backend is not behind a feature flag anymore
https://github.com/docker/dev-tooling-team/issues/244
=> `compose up` and other compose commands running on “Moby” context type.

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/logs.go, cli/cmd/compose/up.go, ecs/local/compose.go, ecs/logs.go, ecs/up.go, example/backend.go, formatter/logs.go, local/compose.go
**What I did**
Refactored the compose API to use a `LogConsumer` callback vs a raw `io.Writer`. Log message then get typed by service/container and can be processed by consumer for output (raw, colored, prefixed, filtered ...)
This refactoring started with the intent to introduce `attachContainerStreams` so we can define `compose.Attach` API method that will be required to implement `compose run`, see https://github.com/docker/compose-cli/issues/940#issuecomment-739770823
/test-ecs
=> Revisit logs/up API to pass a LogConsumer vs io.Writer

cli/cmd/compose/compose.go
**What I did**
https://github.com/docker/dev-tooling-team/issues/244
=> Add a disclaimer message for all `docker compose` commands

local/compose.go, local/e2e/compose_test.go, local/e2e/volume-test/docker-compose.yml
**What I did**
* when creating volumes, don't return previous error of the check to see if volume exists ...
* Add volume creation in compose e2e volume test
Found in several awesome compose examples
=> Fix volume ensure when creating local volume before running services

cli/cmd/compose/compose.go
Fixes ACI / ECS e2e tests
**What I did**
display disclaimer only if context type is local or default("moby")
https://github.com/docker/compose-cli/runs/1511471331
/test-aci
=> Display compose experimental disclaimer only for local context type or moby (default) context type

local/build.go
**What I did**
Fixed `docker compose up` when the build section has the `target` defined.
=> Pass the target to buildkit

local/compose.go
**What I did**
* Avoid returning nil error and nil project in `projectFromContainerLabels`, return project with a name and no service if there are no containers
* Test compose networks get removed after deleting compose containers separately (or compose up that created the network and failed on containers)
=> Ensure down continues (removes networks) even if containers have been removed already

tests/e2e/e2e_test.go, tests/framework/mockmetrics.go
**What I did**
If not getting all expected metrics the first time, wait 1 sec and get metrics again
Fixes https://github.com/docker/compose-cli/issues/1033
=> Trying to fix flakyness on metrics e2e tests

tests/aci-e2e/e2e-aci_test.go
**What I did**
Wait 1 sec and retry on ACI `docker prune --force` when we hit this specific SDK error
Fixes https://github.com/docker/compose-cli/issues/974
/test-aci
=> Trying to fix ACI flakyness on docker prune --force

cli/cmd/compose/build.go, cli/cmd/compose/down.go, cli/cmd/compose/list.go, cli/cmd/compose/logs.go, cli/cmd/compose/ps.go, cli/cmd/compose/pull.go, cli/cmd/compose/push.go, cli/cmd/compose/up.go
**What I did**
Mainly take help labels from docker-compose
```
Available Commands:
build       Build or rebuild services
convert     Converts the compose file to a cloud format (default: cloudformation)
down        Stop and remove containers, networks
logs        View output from containers
ls          List running compose projects
ps          List containers
pull        Pull service images
push        Push service images
up          Create and start containers
```
Fixes #1035 
=> Adding short description to improve help on compose subcommands

cli/cmd/compose/compose.go, cli/cmd/compose/up.go, go.mod, go.sum, local/compose/build.go, tests/compose-e2e/compose_test.go
**What I did**
* do not rebuild by default if not needed
* Added first use of compose pull_policy and `compose up --build` to allow to force rebuild.
* extended e2e tests
Fixes #1025 
=> No rebuild on compose up if image already exists by default

local/compose/attach.go
**What I did**
Check if stdin is nil before closing, `getContainerStreams` returns a `nil` `stdin` if the container is already running
=> Check if stdin is nil before closing

Makefile
**What I did**
set `BUILDX_NO_DEFAULT_LOAD=1` in the Makefile.
When we do not require an image output from a `docker build` command, we should not export an image as this just wastes time.
This requires that build uses buildx which can be enabled with `docker buildx install`
=> Do not unnecessarily export images

aci/convert/container.go, aci/convert/ports.go, aci/convert/ports_test.go
**What I did**
* Add protocol conversion when creating ACI container group for tcp/udp
* deploy and check runtime `docker inspect` also returns the correct port protocol.
* added an error for unknown protocols
Fixes #985 
/test-aci
=> ACI: Allow setting protocol when publishing ports

cli/mobycli/exec.go
It seems some tabs have been replaced by spaces in CLI 20.10.
We need to install docker CLI ourselves in Github actions nodes, local e2e was failing locally, I assume this is since CLI 20.10.
symptom: `docker --context aci images` was returning 
`unknown command "images" for "docker"` 
instead of 
`Command "images" not available in current context (test-example), you can use the "default" context to run this command`
**What I did**
* replace exact tab matching by regex matching any space
=> Make Moby command detection (based on help output) more robust.

ecs/aws.go, ecs/awsResources.go, ecs/aws_mock.go, ecs/cloudformation_test.go, ecs/sdk.go
**What I did**
Add ability to detect "public subnets" and only consider those when building the stack's network configuration.
Note: private subnets (i.e. not associated with an Internet Gateway) don't make sense for Docker ECS integration as service would not be able to pull sidecar images from DockerHub.
https://github.com/docker/compose-cli/issues/921
/test-ecs
=> Only consider public subnets

Makefile, tests/compose-e2e/compose_test.go, tests/compose-e2e/fixtures/sentences/docker-compose.yaml
**What I did**
* Add compose e2e folder in e2e makefile invocation.
We could move e2e tests closer to each backend code (unrelated to fixing this CI issue here) : aci E2E tests under `/aci/e2e` , local E2E under `/local/e2e` (that already has some), ... . WDYT @rumpl @ndeloof ?
Compose local E2E tests not run in CI
=> Ensure local compose E2E are run in CI.

tests/aci-e2e/e2e-aci_test.go
some fixed in a804136b1c395f3a7d958d2516c8eec45b126ce7 (fixing `docker prune --dry-run --force` , exact same issue here with `docker prune --force`)
**What I did**
* detect strange ACI error message and retry docker prune --force one sec later
https://github.com/docker/compose-cli/runs/1557354494#step:6:196
/test-aci
=> Avoiding more ACI flakyness

Makefile
(buildkit failing with `failed to mount C:\ProgramData\docker\tmp\buildkit-mount370086869: [{Type:bind Source:C:\ProgramData\docker\windowsfilter\y3952h88q6ikevun9li41hjcb Options:[rbind ro]}]: invalid windows mount type: 'bind’`).
**What I did**
https://github.com/docker/compose-cli/runs/1557667137#step:7:465
/test-windows
=> Do not run compose local e2e tests on windows GHA nodes for now

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/logs.go, ecs/local/compose.go, ecs/logs.go, example/backend.go, local/compose/logs.go
**What I did**
Implemented a CLI filter to only collect logs for selected services.
Suboptimal on local, but works on all backends
https://github.com/docker/compose-cli/issues/987
=> allow to collect logs for a subset of project services

tests/e2e/e2e_test.go, tests/framework/mockmetrics.go
**What I did**
* cleanup previous fix (#1038) that didn't correct the root cause
* realised the metrics mock server was started totally async, need to wait a bit
* could not find an easy API to check the server is ready, wait for 500 ms, other solutions would loop and wait anyway... 
Fixes #1033 
=> Fix metrics flakyness

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/convert.go, cli/cmd/compose/down.go, cli/cmd/compose/up.go, ecs/cloudformation.go, ecs/down.go, ecs/local/backend.go, ecs/local/compose.go, ecs/up.go, example/backend.go, go.mod, local/compose/compose.go, local/compose/down.go, local/compose/logs.go, server/proxy/compose.go, tests/compose-e2e/fixtures/logs-test/compose.yaml, tests/compose-e2e/logs_test.go
**What I did**
Replaced shell-out to `docker-compose` with delegation to local backend compose implementation
This also introduces `removeOrphaned` option on compose.Down api, not explosed to the CLI yet
close https://github.com/docker/compose-cli/issues/928
https://github.com/docker/compose-cli/issues/1070
=> use compose-in-go code to implement local ECS simulation context

cli/cmd/compose/compose.go
**What I did**
Added support for `.env` files when loading a compose file to align with docker-compose
https://github.com/docker/compose-cli/issues/635
=> Add support for .env file when loading compose files

docs/aci-compose-features.md, docs/aci-container-features.md, docs/architecture.md, docs/ecs-architecture.md, docs/ecs-compose-examples.md, docs/ecs-compose-features.md
Metadata required to include these docs in docs.docker.com
**What I did**
https://github.com/docker/docker.github.io/pull/11865
=> Add metadata for docs included in docs.docker.com 

local/compose/pull.go, local/compose/push.go
**What I did**
ignore service which have no `image` attribute on push/pull
to align with docker-compose:
https://github.com/docker/compose/blob/2e273c50293726a7f8cc5751e90e788613052594/compose/service.py#L1249
https://github.com/docker/compose/blob/2e273c50293726a7f8cc5751e90e788613052594/compose/service.py#L1272
report to user as "skipped"
close https://github.com/docker/compose-cli/issues/1040
=> ignore services without image attribute

tests/ecs-e2e/e2e-ecs_test.go
**What I did**
* secrets E2E test failure was not due to race condition after creating secrets, but AWS secrets needed some cleanup
see https://github.com/docker/compose-cli/runs/1651760200#step:7:32
* removed newly added retry, only confusing
https://github.com/docker/compose-cli/runs/1651760200#step:7:32
This reproduced for every build in the CI, I manually removed these `Mysecret1Secret-xxxx` secrets, and the issue went away. 
Not sure what is the underlying reason in ECS, do we need to manage pagination when listing ECS secrets ?
/test-ecs
=> Remove unnecessary retry in ECS secrets test

local/compose/down.go
in case some container is still up for any reason (happened in some E2E test once)
**What I did**
* set remove (Force = true)
Fixes https://github.com/docker/compose-cli/issues/1097
=> When running compose down, remove containers with Force=true 

README.md, tests/aci-e2e/e2e-aci_test.go
**What I did**
* Fix assertion when retrying docker prune after flaky error
* Try to fix "ContainerGroupTransitioning" flaky error on container restart, with a retry
https://github.com/docker/compose-cli/runs/1655479475#step:6:227
/test-aci
=> Improving ACI E2E tests with platform flakyness

ecs/convert.go, go.mod, go.sum, local/compose/create.go
Add GPU support to  `docker compose` to align it with `docker-compose`.
Closes https://github.com/docker/compose-cli/issues/1092
```yaml
services:
test:
image: tensorflow/tensorflow:latest-gpu
command: python -c "import tensorflow as tf;print(tf.test.gpu_device_name())"
deploy:
resources:
reservations:
devices:
- driver: nvidia
capabilities: [gpu]
```
```
$ docker compose up
The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at https://github.com/docker/compose-cli
[+] Running 2/1
⠿ Network "test_default"  Created                                                               0.5s
⠿ test_test_1             Created                                                               0.0s
Attaching to test_test_1
test    | …
```
=> Add GPU support via DeviceRequests

docs/ecs-compose-examples.md, ecs/compatibility.go, ecs/convert.go, ecs/gpu.go
Fixes https://github.com/docker/dev-tooling-team/issues/262
```yaml
...
reservations:
memory: 16Gb
cpus: "8"
generic_resources:
- discrete_resource_spec:
kind: gpus
value: 4
```
must be equivalent to 
```yaml
...
reservations:
memory: 16Gb
cpus: "8"
devices:
- driver: nvidia
count: 4
capabilities: [gpu]
```
/test-ecs
=> ECS: Parse DeviceRequest struct for GPU access setup

formatter/logs.go, local/compose/attach.go, local/compose/compose.go, local/compose/containers.go, local/compose/convergence.go, local/compose/convergence_test.go, local/compose/create.go, local/compose/down.go, local/compose/ps.go
**What I did**
This applies `container_name` when available in the service definition.
Resolves https://github.com/docker/compose-cli/issues/1046
=> Use `container_name` property on service

local/compose/create.go, local/compose/util.go
Implement compose secrets via bind mounts. 
```yaml
services:
test:
image: nginx
secrets:
- my_secret
secrets:
my_secret:
file: ./my_secret.txt
```
```shell
$ cat my_secret.txt 
blabla bbla ba
```
```
docker compose up -d
The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at https://github.com/docker/compose-cli
[+] Running 2/1
⠿ Network "test_default"  Created                                                               0.5s
⠿ test_test_1             Created                                                               0.0s
```
```
$ docker exec -it test_test_1 cat /run/secrets/my_secret
blabla bbla ba
```
Closes https://github.com/docker/compose-cli/issues/934
=> Implement secrets via bind-mounts for local compose

metrics/metrics.go
**What I did**
* stop sending metrics when compose-cli is executed as a CLI backend, as Docker CLI will handle metrics in this case
manually tested with local build of CLI including backend capabilities and metrics.
This is zero impact on the behavior of the compose cli if not used as a CLI backend
https://github.com/docker/dev-tooling-team/issues/248
=> Do not send metrics if executed as CLI backend

tests/aci-e2e/e2e-aci_test.go
**What I did**
Change call to restart ACI container to allow checking error and restarting if the first invocation fails
https://github.com/docker/compose-cli/runs/1670059596#step:9:227
/test-aci
=> Do not fil on first error on ACI restart, allow trying a second time

ecs/aws.go, ecs/awsResources.go, ecs/aws_mock.go, ecs/sdk.go
**What I did**
Retrieve VPC and Subnets a LoadBalancer is attached to, and use them to deploy the application
Also check conflicts with c-aws-vpc if set
https://github.com/docker/compose-cli/issues/996
/test-ecs
=> Use LoadBalancer's VPC and subnet when x-aws-loadbalancer is set

aci/convert/convert.go, tests/compose-e2e/fixtures/volume-test/docker-compose.yml, tests/composefiles/demo_multi_port.yaml
Not supporting container name also has the side effect of network names not being resolved.
(Note container_name is used in several MSFT examples, this is likely to be used just because of examples and documentation)
**What I did**
* Set ACI container name to `container_name` if specified in compose file
* Add network alias `container_name` (if specified) in addition to service name, same behaviour as docker-compose
Quite possibly the reason for https://github.com/docker/compose-cli/issues/986
/test-aci
=> Support container_name in ACI and add network alias in dns sidecar.

tests/compose-e2e/compose_test.go
Hopefully this will fix flakyness ont his test
**What I did**
Fixes https://github.com/docker/compose-cli/issues/1121
=> Move check that container exited after inspecting container

local/compose/create.go
**What I did**
removed TODO
feature was actually introduced by https://github.com/docker/compose-cli/commit/f65a0d372024426896a4034eb741508e7722de8c
Close https://github.com/docker/compose-cli/issues/932
=> We actually support volume labels and driver_opts

ecs/awsResources.go, ecs/testdata/simple/simple-cloudformation-conversion.golden, ecs/volumes.go, go.mod, go.sum, local/compose/build.go, local/compose/create.go, local/compose/create_test.go, tests/compose-e2e/compose_test.go, tests/compose-e2e/fixtures/network-test/docker-compose.yaml, tests/compose-e2e/fixtures/volume-test/docker-compose.yml
**What I did**
* move all network name normalizaiton into compose-go, same for volumes, secrets, configs
* add network e2e on networks with specified name
* small refactoring & unit tests
https://github.com/docker/dev-tooling-team/issues/257
/test-aci
/test-ecs
=> Compose unit test networks & volumes

api/compose/api.go, cli/cmd/compose/build.go, cli/cmd/compose/compose.go, cli/cmd/compose/convert.go, cli/cmd/compose/down.go, cli/cmd/compose/pull.go, cli/cmd/compose/push.go, cli/cmd/compose/up.go, local/compose/down.go
**What I did**
Pass `Project` to Down if it was set on command line, so we ddon't need to search for compose files
https://github.com/docker/compose-cli/issues/1141
=> run "down" using project if it was set for command

.github/stale.yml
**What I did**
Enable stale bot (https://github.com/apps/stale) so obsolete/inactive issues get currated.
Using the same configuration as docker/compose
=> enable and configure stalebot

local/compose/convergence.go, local/compose/create.go, local/compose/util.go, tests/compose-e2e/compose_test.go
Align with docker-compose volume setup.
Fixes https://github.com/docker/compose-cli/issues/1117
_docker-compose.yml_
```
version: "3.8"
services:
test:
image: test/hello
build: ./backend
ports:
- 80:8080
secrets:
- my_secret                        # bind-mount
volumes:
- testvolume:/vol                  # named volume
- type: bind                       # bind-mount
source: ../nginx
target: /compose
- ./backend/creds:/src/creds.txt   # bind-mount
- /anonymous                       # anonymous volume
- externalvolume:/external         # external volume
- type: tmpfs                      # tmpfs mount
target: /temp
volumes:
testvolume:
externalvolume:
external: True
name: myvol
secrets:
my_secret:
file: ./secrets/mysecret.txt
```
```
$ docker-compose up -d
$ docker inspect hello_test_1 | jq …
```
=> Local: Volumes implementation - align with docker-compose

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/list.go, cli/server/proxy/compose.go, ecs/aws.go, ecs/aws_mock.go, ecs/e2e/ecs/e2e-ecs_test.go, ecs/list.go, ecs/local/compose.go, ecs/sdk.go, local/compose/ls.go
**What I did**
Introduced `--filter` option on `compose ls` so one can limit output
removed support for project name which doesn't make much sense when listing stacks
/test-ecs
/test-aci
/test-windows
=> introduce `--filter` option on `compose ls`

api/context/store/contextmetadata.go, api/context/store/store.go, cli/cmd/context/create_kube.go, go.mod, kube/charts/kubernetes/context.go, kube/context.go
Refactored the context create: 
- renamed `kubernetes` type to `k8s` (conflict with the legacy `kubernetes` endpoint from Docker contexts).
- parse kubeconfigs for the list of contexts
- `.FromEnvironment` option should enable the use of the current context in a kubeconfig passed via `$KUBECONFIG`
```
$ docker context create k8s test
? Create a Docker context using:  [Use arrows to move, type to filter]
> Context from kubeconfig file
Kubernetes environment variables
```
```
$ docker context create k8s test
? Create a Docker context using: Context from kubeconfig file
? Select kubeconfig context  [Use arrows to move, type to filter]
> kind-kind
kind-cluster2
```
```
$ docker context create k8s test
? Create a Docker context using: Context from kubeconfig file
? Select kubeconfig context …
```
=> Refactor kubernetes context create

.github/workflows/ci.yml, Makefile, builder.Makefile, kube/charts/kubernetes/context.go, kube/charts/kubernetes/placement_test.go, kube/charts/kubernetes/pod_test.go, kube/compose.go, kube/context.go, local/compose/down.go, local/compose/stop.go
Fixed some tests, let some failing test still fail, to be fixed
**What I did**
* updated makefile & GHA CI to run kube test & lint
* fixed test compile errors, helper methods
* Did not fix all tests, that were already failing / ignored
=> CI build, lint & test kube backend.

cli/cmd/compose/start.go, cli/cmd/compose/up.go
**What I did**
* do not mix progress and attaching to logs in `docker compose start`
* when not attaching to logs, display container start progress in `compose up` and `compose start` 
Follow up on https://github.com/docker/compose-cli/pull/1180
Just to check if there isn't any missed side effect on other backends: 
/test-aci
/test-ecs
=> Fix compose start display

cli/cmd/compose/compose.go, cli/cmd/compose/create.go, cli/cmd/compose/up.go
**What I did**
Introduce `docker compose create` command for parity with docker-compose
**Note**
This de-deprecates `create` command (https://github.com/docker/compose/commit/40c05cfc1e33077f7fe35ebabf64af3968ef58c8)
to maintain parity with `docker create` command and avoid ambiguous `--no-xyz=true` flags
=> introduce compose create command

go.mod, kube/backend.go, kube/charts/charts.go, kube/charts/helm/helm.go, kube/charts/kubernetes/context.go, kube/compose.go
- Load the kubeconfig 
- Target cluster from the docker context for deployment.
[TODO] - use the progress writer for the output
```
$ docker context create kubernetes kube1 --description "Kube cluster 1"
? Create a Docker context using: Context from kubeconfig file
? Select kubeconfig context kind-cluster1
Successfully created kube context "kube1"
```
```
$ docker context create kubernetes kube2 --description "Kube cluster 2"
? Create a Docker context using: Context from kubeconfig file
? Select kubeconfig context kind-cluster2
Successfully created kube context "kube2"
```
```
$ docker --context kube1 compose up
2021/01/28 14:30:03 checking 5 resources for changes
2021/01/28 14:30:03 Created a new Service called "db" in default
2021/01/28 14:30:03 Created a new Service called "wordpress" …
```
=> Kube backend: Target the cluster referenced by the docker context

api/compose/api.go, cli/cmd/compose/compose.go, cli/cmd/compose/logs.go, ecs/aws.go, ecs/aws_mock.go, ecs/logs.go, ecs/sdk.go, local/compose/create.go, local/compose/down.go, local/compose/logs.go, local/compose/stop.go
**What I did**
introduce compose logs `--tail` and `--follow` options
`--tail` is only supported on local backend
https://github.com/docker/compose-cli/issues/1059
/test-aci
/test-ecs
=> introduce compose logs --tail and --follow options

Makefile, kube/e2e/compose_test.go
**What I did**
* See twice ACI timeout failures on main
* Set timeout to 15 mins
/test-aci
=> ACI timeout moved from 10 to 15 mins

.github/labeler.yml, kube/charts/kubernetes/kube.go, kube/charts/kubernetes/kube_test.go, kube/e2e/kube-simple-demo/demo_sentences.yaml, local/compose/labels.go
**What I did**
* Add headless service for internal cross-service communication
* Services exposing ports mapped to load-balancer
* add some unit tests
* Added a sample composefile that deploys successfuly on Desktop kube cluster
Fixes https://github.com/docker/compose-cli/issues/1182
=> Support exposing ports and cross-service communication

api/compose/api.go, cli/cmd/compose/ps.go, local/compose/ps.go
**What I did**
Inspect containers on `compose ps` to get health status
closes #1198
**sample output**
```
NAME                SERVICE             STATE               HEALTH              PORTS
nicolas_test_1      test                running             healthy             
nicolas_toto_1      toto                running             healthy             
nicolas_truc_1      truc                running             unhealthy           
```
**Note**
This PR doesn't propose ECS implementation, but AFAIK the `DescribeService` API would also return health status
=> Add HEALTH column to compose ps

.github/workflows/kube-tests.yml, Makefile, cli/cmd/context/create_kube.go, kube/context.go, kube/e2e/compose_test.go, utils/e2e/framework.go
**What I did**
* Start kind cluster, wait... 
* deploy compose sample sentence stack. Wait... 
* check all services are wired up and we can get access service exposed on port 80
* Added Kube CI workflow (need to install jq, kubectl, kind)
We should probably check if a specific kube cluster already exists locally and reuse it, for local tests that will make things a lot quicker (but more risks of starting in a non totally clean env locally).
Fixes https://github.com/docker/compose-cli/issues/1192
/test-kube
=> First kube e2e. Adapted context create kubernetes command to allow non interactive mode.

.github/PULL_REQUEST_TEMPLATE.md, kube/context.go, kube/context_test.go, kube/e2e/compose_test.go
**What I did**
Set default description if not user-provided in `docker context create kubernetes` command
```
$ ./bin/docker context ls
NAME                TYPE                DESCRIPTION                                                                           DOCKER ENDPOINT               KUBERNETES ENDPOINT   ORCHESTRATOR
default *           moby                Current DOCKER_HOST based configuration                                               unix:///var/run/docker.sock                         swarm
ecscontext          ecs                 us-west-2                                                                                                                                 
kube-e2e-ctx        kube                kind-e2e (in …
```
=> Kube ctx description

local/e2e/compose/compose_test.go, local/e2e/compose/fixtures/sentences/compose.yaml
**What I did**
* while preparing a demo, added healthcheck to compose file and then added `compose ps` to local compose e2e tests
=> Adding e2e test for local compose healthcheck in compose ps

api/progress/tty.go, api/progress/tty_test.go
**What I did**
* If endTime is not set when displaying elapsed time, init as starTime (=> elapsed = 0)
Fixes https://github.com/docker/compose-cli/issues/1227
=> Avoid negative elapsed the display when only one event is sent.

cli/cmd/compose/down.go
**What I did**
* just expose the flag, everything was already wired to the backend
Fixes https://github.com/docker/compose-cli/issues/1166
=> Expose `—remove-orphans` in compose down command

kube/resources/kube.go, kube/resources/kube_test.go, kube/resources/pod_test.go
Kube resource name follow the form `<PROJECT>-<SERVICE>`. (“_” are not allowed there, using “-“. Project names can include “-“, so we can’t parse back to retrieve project and service names, we MUST rely on labels.
**What I did**
* Add `myproject-` as a prefix to kube resource names
* * unit tests
/kube-test
=> Prefix kube resource with compose project name to avoid name clashes between projects.

kube/resources/kube.go, kube/resources/kube_test.go, kube/resources/pod_test.go
This breaks networking between containers within a Compose project, since DNS entries are based on service name (and are not scoped to projects)
This reverts commit 6b61902a23763fd51d6a5e864cc568b33058b06e.
**What I did**
/test-kube
=> Revert "Prefix kube resource with compose project name "

kube/client/client.go, kube/client/client_test.go, kube/compose.go, kube/e2e/compose_test.go
**What I did**
* List pods filtering on labels for project name 
* transform pods to compose.ContainerSummary
https://github.com/docker/compose-cli/issues/1195
This does not yet retrieve containers port data, need to reconcile pod data and kube services to get this
/test-kube
=> Kube compose ps

local/compose/labels.go, local/compose/logs.go
**What I did**
Exclude one_off container as we collect project containers for `compose logs`
Ue container name for line prefix, not ID (sha)
https://github.com/docker/compose-cli/issues/1248
=> Filter out one_off containers on `compose logs`

cli/cmd/compose/ps.go, local/e2e/compose/compose_test.go, local/e2e/compose/fixtures/sentences/compose.yaml
**What I did**
* Combine values from fields “state” and “health”. 
* Rename column STATE => STATUS.
=> Remove the HEALTH column in `docker compose ps` 

aci/e2e/e2e-aci_test.go, cli/metrics/metrics_test.go, ecs/e2e/ecs/e2e-ecs_test.go, kube/e2e/compose_test.go
**What I did**
* move common compose flags before the compose subcommand
Red tests on https://github.com/docker/compose-cli/commit/a5b148bda11324309ef75e7538254dd27020ef27 and previous commits on main
/test-aci
/test-windows
/test-ecs
/test-kube
=> Adapt e2e tests to compose flag order

kube/client/client.go, kube/compose.go, kube/e2e/compose_test.go, local/compose/attach.go, local/compose/logs.go, utils/logconsumer.go
Add `compose logs` for the Kubernetes backend.
Closes https://github.com/docker/compose-cli/issues/1206
```
$ docker compose logs
web-5474d97f7c-9v7fc | Listening on port 80
web-5474d97f7c-9v7fc | 2021/02/04 19:07:33 /noun Calling http://10.244.0.9:8080/noun
web-5474d97f7c-9v7fc | 2021/02/04 19:07:33 /adjective Calling http://10.244.0.9:8080/adjective
...
web-5474d97f7c-9v7fc | 2021/02/04 19:20:21 /noun Calling http://10.244.0.9:8080/noun
web-5474d97f7c-9v7fc | 2021/02/04 19:20:21 /adjective Calling http://10.244.0.9:8080/adjective
words-8454b58564-6nrvk | {"word":"møby døck"}
words-8454b58564-6nrvk | {"word":"the gløriøus"}
words-8454b58564-6nrvk | {"word":"laptøp"}
words-8454b58564-6nrvk | {"word":"debugs"}
words-8454b58564-6nrvk | {"word":"the impressive"}
db-5b468cc7d-x7xnb | The …
```
=> Kube backend: Implement `compose logs`

local/e2e/compose/compose_test.go, local/e2e/compose/fixtures/volume-test/compose.yml
**What I did**
Add e2e tests on configs and secrets
Resolves https://github.com/docker/compose-cli/issues/1242
=> Add content based e2e tests for configs and secrets

api/progress/tty.go, local/compose/down.go
**What I did**
* Display a warning from local backend if `docker compose down` finds nothing to remove (no containers nor network)
```
[+] Running 1/0
⠿ sentences  Warning: No resource found to remove      
```
`docker-compose` displays a warning on no network to remove in the same case (still exits with zero)
=> Down warning when nothing to remove

api/compose/api.go, cli/cmd/compose/convert.go, cli/cmd/compose/convert_kube.go, kube/compose.go, kube/helm/chart.go
Add `compose convert` command to display the content of the chart files generated from the Compose file.
Closes https://github.com/docker/compose-cli/issues/1207
Save generated chart files to a directory:
```
$ docker compose convert --output-dir /tmp/test
model saved to /tmp/test
$ ls /tmp/test/
Chart.yaml  README.md  templates
```
```
$ docker compose convert --help
Converts the compose file to platform's canonical format
Usage:
docker compose convert SERVICES [flags]
Aliases:
convert, config
Flags:
--format string       Format the output. Values: [yaml | json] (default "yaml")
-h, --help                help for convert
--output-dir string   Save to directory
```
Check chart content:
```
$ docker  compose convert
README.md
---------
This chart was created by converting a Compose file …
```
=> Kube backend: Add `compose convert`

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/run.go, cli/cmd/compose/start.go, cli/cmd/compose/up.go, cli/cmd/exit.go, cli/formatter/logs.go, cli/main.go, ecs/local/compose.go, ecs/logs.go, ecs/up.go, go.sum, kube/compose.go, local/compose/attach.go, local/compose/compose.go, local/compose/containers.go, local/compose/logs.go, local/compose/start.go, local/e2e/compose/cascade_stop_test.go, local/e2e/compose/fixtures/cascade-stop-test/compose.yaml, utils/logconsumer.go
**What I did**
Introduce "--abort-on-container-exit" and "--exit-code-from"
use ContainerWait API to capture container termination and exit code
changed architecture to pull logs and events from cli, so that we can easily react to "container exit" event
replace https://github.com/docker/compose-cli/pull/1259
fix https://github.com/docker/compose-cli/issues/1209
=> Exit code from

cli/cmd/compose/run.go, local/compose/create.go, local/e2e/compose/compose_test.go
**What I did**
* Fix orphans warning displayed when running `docker compose up SERVICE`
* Fix orphans warning displayed when running `docker compose run ...`
Fixes https://github.com/docker/compose-cli/issues/1199
=> Compose orphans warning

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/run.go, ecs/local/compose.go, ecs/run.go, kube/compose.go, local/compose/attach.go, local/compose/convergence.go, local/compose/run.go
**What I did**
consider "exited" container from a previous run as "Created" so we just need to invoke _start_ 
https://github.com/docker/compose-cli/issues/1289
=> detect stopped containers as "Created"

api/compose/api.go, cli/cmd/compose/logs.go, cli/cmd/compose/start.go, cli/cmd/compose/up.go, cli/formatter/colors.go, cli/formatter/logs.go, local/compose/attach.go, local/compose/containers.go, utils/logconsumer.go
**What I did**
Register containers being attached sorted by name before we start pulling logs. Doing so assigned color is predictable
Also introduce --no-color and --no-log-prefix for parity with docker-compose
fix https://github.com/docker/compose-cli/issues/1271
fix https://github.com/docker/compose-cli/issues/1270
=> make color assignment predictable and option to disable prefixes/colors

cli/cmd/compose/create.go
**What I did**
added --force-recreate and --no-recreate flags to create command
implementation code already exists on up
https://github.com/docker/compose-cli/issues/1277
=> introduce create --force-recreate and --no-recreate

api/compose/api.go, cli/cmd/compose/up.go, cli/formatter/logs.go, local/compose/attach.go, local/compose/logs.go, local/compose/start.go
**What I did**
fix color assignment for status message.
container status `xxx exited with code 123` use full container name, while logs use container name without project.
As a side effect, a distinct color is assigned to status message.
This PR changes the container -> color map to rely on container ID, and pass the resource name as part of the event to distinguish both usages
=> fix color assignment on status messages

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/compose.go, cli/cmd/compose/exec.go, cli/main.go, ecs/exec.go, ecs/local/compose.go, kube/compose.go, local/compose/exec.go
Implement `compose exec`
```
$ cat docker-compose.yml 
services:
web:
image: nginx
scale: 2
$ docker compose up -d
...
$ docker ps
CONTAINER ID   IMAGE     COMMAND                  CREATED          STATUS          PORTS     NAMES
26cde46ec576   nginx     "/docker-entrypoint.…"   47 minutes ago   Up 47 minutes   80/tcp    compose-cli_web_1
4ac1cb5fd1b6   nginx     "/docker-entrypoint.…"   47 minutes ago   Up 47 minutes   80/tcp    compose-cli_web_2
```
```
$ docker compose exec web sh -c ls
bin   docker-entrypoint.d   home   media  proc	sbin  tmp
boot  docker-entrypoint.sh  lib    mnt	  root	srv   usr
dev   etc		    lib64  opt	  run	sys   var
```
```
$ ./bin/docker compose exec web bash
root@26cde46ec576:/#
```
```
$ docker compose exec --index=2  web bash
root@4ac1cb5fd1b6:/#
```
```
$ …
```
=> Add `compose exec` command

api/compose/api.go, cli/cmd/compose/logs.go, local/compose/logs.go
**What I did**
Introduced `--timestamps` option on `compose logs`
https://github.com/docker/compose-cli/issues/1272
=> introduce logs --timestamp

cli/cmd/compose/ps.go
Add `compose ps` flag.
```
services:
web:
image: nginx
ports:
- 8080:80
test1:
image: nginx
scale: 3
test2:
image: nginx
```
```
$ docker compose ps
NAME                  SERVICE             STATUS              PORTS
compose-cli_test1_1   test1               running             80/tcp
compose-cli_test1_2   test1               running             80/tcp
compose-cli_test1_3   test1               running             80/tcp
compose-cli_test2_1   test2               running             80/tcp
compose-cli_web_1     web                 running             0.0.0.0:8080->80/tcp
```
```
$ docker compose ps --services
test1
test2
web
```
Closes #1273
=> Add `--services` flag to `compose ps`

cli/cmd/compose/compose.go
**What I did**
fixed os.ENV precendence over env file
https://github.com/docker/compose-cli/issues/1327
=> os ENV has precedence over env file

api/compose/api.go, cli/cmd/compose/up.go, cli/formatter/logs.go, ecs/aws.go, ecs/aws_mock.go, ecs/sdk.go, kube/client/client.go, local/compose/logs.go, utils/logs.go
**What I did**
Pass "service" to LogConsumer so this one can filter events accordingly
Fix e2e kube failure on main
/test-kube
=> pass service to LogConsumer

.github/workflows/ci.yml
**What I did**
https://github.com/docker/compose-cli/actions/runs/588864117
=> Fixes GH Action config

cli/cmd/compose/logs.go
**What I did**
is in the title
https://github.com/docker/compose-cli/runs/1952730636
=> Fix linter

cli/cmd/compose/logs.go
**What I did**
add `f` shorthand for `docker compose --follow`
Fixes #1060 
=> Allow `docker compose logs -f` for compatibility

Makefile
=> Add make install to symlink cli from `make cli`

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/compose.go, cli/cmd/compose/pause.go, ecs/local/compose.go, ecs/up.go, kube/compose.go, local/compose/pause.go
**What I did**
Introduced `compose pause` and `compose unpause` commands for parity with docker-compose
=> introduce pause and unpause commands

aci/etchosts/Dockerfile, ecs/resolv/Dockerfile, ecs/secrets/Dockerfile
**What I did**
setting GO111MODULE=auto to let it detect, and run as before
(cf https://blog.golang.org/go116-module-changes)
red CI on main
=> Fix sidecar Dockerfiles : Go 1.16 uses go modules by default

cli/cmd/compose/compose.go, cli/main.go
**What I did**
only display experimental warning when compose command fails
note: cobra directly return on error, PersistentPostRun is not executed, so I eventually used a global variable :'(
https://github.com/docker/compose-cli/issues/1108
=> only display experimental warning on command error

api/compose/api.go, api/compose/api_test.go, cli/cmd/compose/run.go, go.mod, local/compose/run.go
**What I did**
extended compose run with a few more options
*  --name NAME Assign a name to the container
* --entrypoint CMD Override the entrypoint of the image.
* -e KEY=VAL Set an environment variable (can be used multiple times)
* -l, --label KEY=VAL Add or override a label (can be used multiple times)
* -u, --user="" Run as specified username or uid
* -T Disable pseudo-tty allocation. By default docker-compose run allocates a TTY.
* -w, --workdir="" Working directory inside the container
=> introduce a few more `compose run` options

api/compose/api.go, cli/cmd/compose/up.go
**What I did**
sync stop on user cancel with container logs display
Fixes #1342 
=> Stop displaying logs when user cancels compose up, to not mix with stop progress display

aci/e2e/e2e-aci_test.go
**What I did**
do not reuse ACI container name when trying to workaround flaky ACI issue
https://github.com/docker/compose-cli/runs/1963218029#step:9:256
/test-windows
/test-aci
=> trying to better work around ACI flaky weird states

.gitignore, aci/backend.go, aci/backend_test.go, aci/cloud.go, aci/convert/registry_credentials.go, aci/convert/registry_credentials_test.go, aci/login/client.go, aci/login/client_test.go, aci/login/cloud_environment.go, aci/login/cloud_environment_test.go, aci/login/helper.go, aci/login/login.go, aci/login/login_test.go, aci/login/token_store.go, cli/cmd/login/azurelogin.go
Signed-off-by: Karol Zadora-Przylecki <karolz@microsoft.com>
**What I did**
Added a notion of "cloud environment" for Azure integration. This allows Docker CLI to work with "sovereign" clouds like Azure China, Azure US Government etc.
Fixes https://github.com/docker/compose-cli/issues/658
This PR does not include documentation changes
This PR does not add new E2E (integration) tests--I was not sure if you want to have any that target non-public Azure clouds. Even for teams inside Microsoft it is not always the case that we have *automated* tests targeting non-public clouds, so I think unit tests are good enough for a start.
=> Add Azure sovereign cloud support

go.sum, local/compose/build.go, local/compose/scan_suggest.go, local/e2e/compose/fixtures/build-test/compose.yml
**What I did**
* Add scan suggest message at the end of `docker compose build`, and end of build section when `docker compose up`
* check scan plugin is available before displaying message
* Allow users to turn this off setting `DOCKER_SCAN_SUGGEST = false`
* Do not display message if user has already used scan command
```
$ ./bin/docker compose -f ./local/e2e/compose/fixtures/build-test/compose.yml build
...
=> [build-test_nginx] exporting to image  
=> => exporting layers            
=> => writing image sha256:f727547da0e5aa30472c3705fd70bfe02ce300e50be0665eca05b6482bdd1aa9        
=> => naming to docker.io/gtardif/custom-nginx:1.0 
=> => naming to docker.io/library/build-test_nginx       
Try scanning the image you have just built to identify vulnerabilities with Docker’s new security …
```
=> Scan suggest message when compose build / compose up

aci/e2e/e2e-aci_test.go
**What I did**
* invoke ACI `docker run` workaround async and wait for the container to be running, as the run call is not returning in this crappy state
/test-aci
/test-windows
=> ACI workaround invocation does not return, but container is actually running OK, trying to not block on this.

.github/workflows/ci.yml
**What I did**
run cross platform validation build on main, but not for every PR, useless
CI builds are too sloooow
=> Validate cross build on all platforms only on the main branch, not every PR

cli/cmd/compose/compose.go, local/e2e/compose/compose_build_test.go, local/e2e/compose/compose_test.go, local/e2e/compose/volumes_test.go
This fixes the ambiguity between `--project-directory` and `--workdir`
`--project-directory` is the one passed to `compose-go` to resolve compose files
`--workdir` is passed to commands `run` and `exec` to provide $PWD to the container before running the command.
Resolves https://github.com/docker/compose-cli/issues/1279
=> Fix --project-directory mix with --workdir

api/compose/api.go, cli/cmd/compose/up.go, local/compose/convergence.go, local/compose/create.go
**What I did**
introduced --renew-anon-volumes so that recreated container **don't** inherit volumes from previous container
https://github.com/docker/compose-cli/issues/1373
=> introduce --renew-anon-volumes

api/compose/api.go, cli/cmd/compose/up.go, local/compose/create.go
**What I did**
Introduced option  `--always-recreate-deps` 
also introduce Up API option to pass a set of "primary" services user interact with. Will be required to implement --attach-dependencies 
https://github.com/docker/compose-cli/issues/1370
=> introduce --always-recreate-deps

local/compose/build.go, local/e2e/compose/compose_build_test.go, local/e2e/compose/fixtures/build-test/compose.yml, local/e2e/compose/fixtures/build-test/nginx-build2/Dockerfile, local/e2e/compose/fixtures/build-test/nginx-build2/static2/index.html
**What I did**
* check if need to force-build image before ignoring present images
came across this when deploying local dos.docker.com with compose
=> Fix compose up --build not forcing rebuild of present image

cli/cmd/login/azurelogin.go
**What I did**
Add list of hardcoded known azure clouds in help message
=> Display available azure cloud names in azure login help

local/compose/build.go, local/compose/scan_suggest.go
**What I did**
See in https://github.com/docker/scan-cli-plugin/blob/main/config/config.go#L40
=> Don’t use context for scan suggest message, use cliconfig.Dir() as in scan plugin for consistency

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/push.go, ecs/local/compose.go, ecs/up.go, kube/compose.go, local/compose/push.go
Added `ignore-push-failures` flag to `compose push`.
```
$ docker compose push
[+] Running 0/16
⠴ Pushing frontend: f009a503aca1 Layer already exists                                                1.5s
...                                                                                                                                 1.5s
⠏ Pushing frontend: 14be20d881b0 Waiting                                                             2.9s
⠏ Pushing frontend: 44f7d9f20b3a Preparing                                                           2.9s
⠴ Pushing backend: cb381a32b229 Waiting                                                              1.5s
The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at …
```
=> Add `ignore-push-failures` flag to `compose push`

api/compose/api.go, cli/cmd/compose/run.go, local/compose/convergence.go, local/compose/run.go, local/e2e/compose/compose_run_test.go
**What I did**
fix https://github.com/docker/compose-cli/issues/1363
fix https://github.com/docker/compose-cli/issues/1364
fix https://github.com/docker/compose-cli/issues/1365
=> implement -v, -p, --service-ports and --use-aliases on compose run

scripts/install/install_linux.sh
**What I did**
I added aarch64 support to the linux installl script, so it doesn't install an incompatible binary on arm64.
There is no issue, should I open one?
=> Add arm64 support to linux install script

api/context/context.go, cli/cmd/version.go, cli/main.go, cli/main_test.go, cli/options/options.go, local/backend.go, local/containers.go, local/e2e/cli-only/e2e_test.go, local/volumes.go
**What I did**
Added common flags to the root command: tls, cert flags etc.
Initialized the API client with the docker/cli `NewAPIClientFromFlags` which processes the config and tls options. This way we avoid duplicating the code that is already in the original cli. 
Set up a secured Docker engine following https://docs.docker.com/engine/security/protect-access/#use-tls-https-to-protect-the-docker-daemon-socket
```
$ docker -H=127.0.0.1:2376 compose ps
The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at https://github.com/docker/compose-cli
Error response from daemon: Client sent an HTTP request to an HTTPS server.
```
```
$ docker --tlsverify --tlscacert=/tmp/certs/ca.pem --tlscert=/tmp/certs/cert.pem …
```
=> Add connection flags to root command

local/e2e/cli-only/e2e_test.go
**What I did**
* validate docker context endpoint is used to get client API, after [change](https://github.com/docker/compose-cli/pull/1400/files#diff-be34777339b68875b2a1c4923c82e1e4761b90f632d6993f8b859a25bcb952feR55) from #1400 
* Add e2e test for context pointing to remote engine
=> Add remote engine context e2e

local/compose/build.go, local/compose/create.go
**What I did**
* Add a few obvious mappings to support more attributes in Composefiles
=> Adding support for compose file attributes

local/compose/create.go
**What I did**
* 2 more obvious mappings from composefile attributes
=> Map composefiles privileged, isolation

local/e2e/compose/compose_test.go
**What I did**
count expected log lines rather than expect a specific order
Flaky test error, one example: https://github.com/docker/compose-cli/pull/1422/checks?check_run_id=2096259440#step:9:15
=> Fix log expectation with random exec order

local/compose/build.go
**What I did**
* Fix mapping of composefile attribute service.build.labels
Following #1417 
=> Fix build image label mapping

local/e2e/compose/compose_run_test.go, local/e2e/compose/compose_test.go
=> Cleanup remaining containers after compose e2e tests

cli/cmd/compose/compose.go, cli/cmd/compose/pull.go
**What I did**
introduce --parallel  and --no-parallel (hidden, deprecated) flags
this prevent backward compatibility issues for users migrating from docker-compose
marked deprecated, implemented as no-op
close https://github.com/docker/compose-cli/issues/1441
=> introduce --parallel  and --no-parallel (hidden, deprecated) flags

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/compose.go, cli/cmd/compose/port.go, cli/cmd/compose/ps.go, cli/cmd/compose/pull.go, cli/cmd/compose/up.go, ecs/local/compose.go, ecs/up.go, kube/compose.go, local/compose/port.go, local/e2e/compose/networks_test.go
**What I did**
introduce `port` command for parity with docker-compose
=> introduce `port` command for parity with docker-compose

local/compose/build.go
**What I did**
Align with docker-compose regarding support for SCM URL as build context
https://github.com/docker/compose/issues/8184
https://github.com/docker/compose-cli/issues/1412
=> Support build.context with git URLs

cli/cmd/compose/convert.go, local/compose/containers.go, local/compose/convergence.go, local/compose/create.go, local/compose/dependencies.go, local/compose/logs.go, utils/hash.go
**What I did**
Implemented --services, --volumes, --hash pseudo-commands on `compose config`
this will prevent compatibility issues with docker-compose
close https://github.com/docker/compose-cli/issues/1442
=> introduce config --services, --volumes, --hash for backward compatibility

cli/cmd/compose/build.go
=> Added deprecated build flags parallel, compress, force-rm

builder.Makefile
**What I did**
Add arm transformation to TAR command
ran `make package` locally and checked the resulting tar includes `docker`
tar packages include binary named `docker-linux-arm64` instead of `docker`
=> Transform binary name for arm packages

scripts/install/test.Dockerfile
**What I did**
* Run Docker tests for install script as non root user
* Test it with `docker build -f scripts/install/test.Dockerfile scripts/install/`
=> Test install script as non root user (still sudoer to be able to install)

cli/cmd/compose/compose.go, cli/cmd/compose/pull.go
**What I did**
Add deprecated `--no-ansi` (hidden) for backward compatibility
=> Deprecated flag --no-ansi

cli/cmd/compose/up.go, local/compose/attach.go, local/compose/start.go
**What I did**
run `containerWait` in background so it's not interrupted by context cancelation, and catch container exit to stop when all are done.
Also add support for second SIGTERM to kill the services (to align with docker-compose)
fix https://github.com/docker/compose-cli/issues/1447
=> Down sigterm

local/compose/create.go, local/e2e/compose/fixtures/ipc-test/compose.yaml, local/e2e/compose/ipc_test.go
Added support for IPC mode:
```yaml
services:
service:
image: busybox
command: top
ipc: "service:shareable"
shareable:
image: busybox
command: top
ipc: shareable
```
```shell
$ docker compose up -d
[+] Running 3/3
⠿ Network "myproject_default"      Created                                                                              0.4s
⠿ Container myproject_shareable_1  Started                                                                              0.7s
⠿ Container myproject_service_1    Started                                                                              1.4s
```
```shell
$ docker inspect myproject_shareable_1 | grep IpcMode
"IpcMode": "shareable",
$ docker inspect myproject_service_1 | grep IpcMode
"IpcMode": …
```
=> Add IPC support

cli/mobycli/exec.go, local/compose/build.go, local/e2e/compose/scan_message_test.go, utils/scan_suggest.go
**What I did**
* Reuse scan_suggest.go (moved to utils/scan_suggest.go in order to use from compose and cli)
* When invoking moby cli, check executed command and display message on successful `docker build` (same rules as before: only if scan not already invoked, for all `docker build` commands, and is not `DOCKER_SCAN_SUGGEST=false`)
* Add e2e tests for `docker build` and `docker compose build`, `docker compose up`
Fixes https://github.com/docker/dev-tooling-team/issues/280
=> Add scan message after docker build, add e2e tests

cli/cmd/compose/convert.go
**What I did**
Align to docker-compose to introduce `config --profiles`
https://github.com/docker/compose/pull/8061
close https://github.com/docker/compose-cli/issues/1476
=> introduce config --profiles for parity with docker-compose

api/compose/api.go, cli/cmd/compose/build.go, local/compose/build.go
Added remaining build flags. Only one applied is the `no-cache` one.
```
$ docker compose build                                                                                                                             
[+] Building 0.3s (18/18) FINISHED                                                                                                                       
=> [nginx-golang-postgres_backend internal] load build definition from Dockerfile                                                                  0.0s
=> => transferring dockerfile: 32B                                                                                                                 0.0s
=> [nginx-golang-postgres_proxy internal] load build definition from Dockerfile …
```
=> Add `no-cache` build flag

go.mod, go.sum
**What I did**
* update goterm lib
* run it on windows to check the progress display is fine
=> Update go term lib with windows support to get terminal size

cli/metrics/client.go
**What I did**
Made metrics' source configurable by environment variable
close https://github.com/docker/dev-tooling-team/issues/291
see https://github.com/docker/compose-v1v2-switch/blob/master/main.go#L181
=> make metrics' source configuration (see compose-switch)

local/compose/create.go
**What I did**
Removed use of `filepath` methods to compute bind mount target, as target OS != source and source's platform-specific format would then be applied.
https://github.com/docker/compose-cli/issues/1493
=> don't use filepath to process remote bind paths

api/progress/noop.go, api/progress/plain.go, api/progress/tty.go, api/progress/writer.go, local/compose/pull.go, local/compose/push.go
**What I did**
This allows progress writer to print plain text after printing all the `tty` messages.
=> Add plain tail messages on progress writer

cli/cmd/compose/up.go
**What I did**
Report an error when there's no service attached to project after profiles and options have been applied. This prevents a deadlock waiting for containers to attach
https://github.com/docker/compose-cli/issues/1491
=> deadlock waiting for services when none selected

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/pause.go, ecs/local/compose.go, ecs/up.go, kube/compose.go, local/compose/attach.go, local/compose/containers.go, local/compose/create.go, local/compose/down.go, local/compose/kill.go, local/compose/labels.go, local/compose/logs.go, local/compose/pause.go, local/compose/ps.go, local/compose/remove.go, local/compose/run.go, local/compose/status.go, local/compose/stop.go, local/compose/top.go
**What I did**
removed requirement for original compose file to invoke pause/unpause commands
also use `getContainers` where possible to reduce code duplication
=> pause/unpause only need project name. use getContainers where possible

aci/compose.go, api/client/compose.go, api/compose/api.go, cli/cmd/compose/compose.go, cli/cmd/compose/images.go, ecs/images.go, ecs/local/compose.go, kube/compose.go, local/compose/images.go, local/e2e/compose/compose_test.go
Added the `compose images` command.
```
[example]$ docker-compose images
Container           Repository       Tag       Image Id       Size  
------------------------------------------------------------------------
example_backend_1    nginx              latest   35c43ace9216   133.1 MB
example_backend_2    nginx              latest   35c43ace9216   133.1 MB
example_backend_3    nginx              latest   35c43ace9216   133.1 MB
example_frontend_1   example_frontend   latest   ca1d0f22403f   22.59 MB
```
```
[example]$ docker compose images
Container            Repository          Tag                 Image Id            Size
example_backend_1    nginx               latest              35c43ace9216        133MB
example_backend_2    nginx               latest              35c43ace9216 …
```
=> Add `compose images` cmd

local/e2e/compose/compose_test.go, local/e2e/compose/fixtures/simple-build-test/compose.yml, local/e2e/compose/fixtures/simple-build-test/nginx-build/Dockerfile, local/e2e/compose/fixtures/simple-build-test/nginx-build/static/index.html, local/e2e/compose/scan_message_test.go
**What I did**
* Avoid 2 parallel tests running the same compose stack, and also opening the same port
Local errors when running `make e2e-local`
=> Avoid race between parallel tests, add specific build sample for scan_message_test

cli/cmd/compose/up.go, local/compose/build.go, local/compose/convergence.go, local/compose/create.go, local/compose/down.go, local/compose/down_test.go, local/compose/run.go, local/compose/status.go
**What I did**
This makes `--build` imply `--force-recreate` in command `up`
Resolves https://github.com/docker/compose-cli/issues/1457
=> Refactor `up --build` behavior

builder.Makefile
Updated release makefile and tested binary on raspberry pi.
```
$ uname -a
Linux raspberry 5.10.27-1-ARCH #1 SMP Tue Apr 6 19:10:41 UTC 2021 armv7l GNU/Linux
```
```
$ ./docker-linux-arm64 --version
-bash: ./docker-linux-arm64: cannot execute binary file: Exec format error
```
```
$ ./docker-linux-armv7 --version
Docker version 20.10.5, build 55c4c88966
```
```
$ ./docker-linux-armv6 --version
Docker version 20.10.5, build 55c4c88966
```
closes https://github.com/docker/compose-cli/issues/1471
=> Release binary for ARM v6 and v7

ecs/up.go
ECS `up` is pulling all events for CFM stack, which may be having some errors in
the history. For example, if CFM stack update was ever cancelled, `up` will be
exiting with code 1 on every run after that cancellation.
Fixes #1112
=> Ignore previous CFM events on update to avoid false positive errors

cli/cmd/compose/compose.go, cli/main.go, cli/metrics/client.go, cli/metrics/compose_errors.go, cli/metrics/definitions.go, local/compose/build.go, local/compose/pull.go, local/e2e/cli-only/e2e_test.go, local/e2e/compose/compose_run_test.go, local/e2e/compose/fixtures/wrong-composefile/build-error.yml, local/e2e/compose/fixtures/wrong-composefile/compose.yml, local/e2e/compose/fixtures/wrong-composefile/service1/Dockerfile, local/e2e/compose/fixtures/wrong-composefile/unknown-image.yml, local/e2e/compose/metrics_test.go, utils/e2e/mockmetrics.go
**What I did**
* Get more detail metrics about failures : composefile parse error, file not found, syntax errors
* return distinct exit codes as well, this will be useful to keep metrics for compose as a CLI plugin.
* ensure `docker compose donw` does not just display help but actually returns an error...
* e2e tests
metrics names, exit codes, failure categorisation is totally subject to discussion
Fixes https://github.com/docker/dev-tooling-team/issues/283
/test-aci
/test-ecs
/test-windows
=> Metrics failure categories

local/compose/build.go
**What I did**
Pass client's config file as Auth to buildkit
close https://github.com/docker/compose-cli/issues/1526
=> pass config file to buildkit for authentication

local/compose/exec.go, local/compose/resize.go, local/compose/run.go
**What I did**
on `compose run` and `compose exec`, monitor terminal resize events to adjust container's tty accordingly
https://github.com/docker/compose-cli/issues/1460
=> resize terminal and monitor SIGWINCH

cli/mobycli/exec.go, local/e2e/cli-only/e2e_test.go
**What I did**
only capture stdout when we run a moby command, so that we don't get stderr mixed
close https://github.com/docker/compose-cli/issues/1515
=> don't include stderr in moby exec output

local/compose/containers.go, local/compose/convergence.go, local/compose/exec.go, local/compose/resize.go, local/compose/run.go
**What I did**
change API call order so we wait for container next exit _before_ we start it, otherwise a container to just run `/bin/true` might terminate before we invoke wait, resulting in daemon error "container xx is not running"
=> only start container once we have a wait channel set, to prevent race

local/compose/create.go
**What I did**
Don't build networkConfig if no network binding is declared
this is same as https://github.com/docker/compose/blob/master/compose/service.py#L817-L818
close https://github.com/docker/dev-tooling-team/issues/301
=> don't set aliasses if no network binding was declared

cli/cmd/compose/convert.go
Fix volume names to print simple volume names instead of `<project>_<volume>`
=> Fix volume names to print simple volume names

local/compose/containers.go, local/compose/convergence.go
**What I did**
ensureScale must ignore oneoff cotainers which don't have a "number" label
should fix https://github.com/docker/compose-cli/issues/1537
fix https://github.com/docker/compose-cli/issues/1561
=> scale must ignore oneoff containers

local/compose/images.go
**What I did**
use mutex to sync concurrent access to map (quick global pass looking for `eg.Go(` )
https://github.com/docker/compose-cli/runs/2295818799 (first time seen)
=> Avoid panic: concurrent map writes

cli/cmd/compose/images.go, local/compose/build.go, local/compose/images.go
When an image is updated locally via pull or build, the containers are not being recreated on `compose up` (service hash is not generated with the image digest but with an image repo/tag that could be reassigned on build).
This fixes also the output of `compose images` when the repo/tag changes (aligns with docker-compose).
```
[example]$ docker compose up -d
[+] Running 3/3
⠿ Container example_backend_1   Running                                                                                                           0.0s
⠿ Container example_backend_2   Running                                                                                                           0.0s
⠿ Container example_frontend_1  Running …
```
=> Set image digest as service image to trigger recreation after build

go.mod, go.sum, local/compose/build.go, local/compose/convergence.go
**What I did**
replace use of WaitContainer with polling on Container.State
there's a risk container terminate before we run WaitContainer, and we never catch "next exit" event. This typically happen with e2e test to run `echo hello`.
=> fix race condition with init containers

utils/hash.go
Some service properties are added at runtime when requiring a build. This makes the config hash to always be different from `compose up` and triggers a restart.
```
$ docker compose build
[+] Building 0.6s (7/7) FINISHED                                                                                                                        
=> [internal] load build definition from Dockerfile                                                                                               0.0s
=> => transferring dockerfile: 31B                                                                                                                0.0s
=> [internal] load .dockerignore                                                                                                                  0.0s
=> => …
```
=> Remove service.Build and service.PullPolicy from config hash

go.mod, go.sum, local/compose/create.go, local/compose/down.go, local/compose/kill_test.go, local/e2e/compose/compose_test.go
This is breaking one Desktop test, and I also ran into this when cleaning up test compose apps manually. 
**What I did**
Ensure we store absolute paths in container labels, and do not try to reconstruct composefile paths with unrealistic logic when reading labels
https://ci-next.docker.com/teams-desktop/blue/organizations/jenkins/desktop%2Fdesktop-test-single-pr-mac/detail/desktop-test-single-pr-mac/84670/pipeline
=> Fix down not working if run from a different folder than up, because container labels stored relative paths

docs/ecs-architecture.md
**What I did**
Fixed a minor typo
None
=> fix typo in ecs-architecture.md

scripts/install/install_linux.sh, scripts/install/test.Dockerfile
**What I did**
scripted linux install installs compose-cli binary + compose cli plugin
=> Install compose cli plugin in addition to compose-cli binary with scripted install

cli/main.go
**What I did**
removed "compose" command for default context type, being implemented as a CLI plugin
=> On default context, "compose" is implemented by CLI Plugin

local/e2e/compose/cancel_test.go, local/e2e/compose/compose_test.go, local/e2e/compose/metrics_test.go
Signed-off-by: guillaume.tardif <guillaume.tardif@gmail.com>
**What I did**
Manually run compose tests on my win dev machine (with Docker Desktop), adapted a few path issues.
(not running in CI as GHA CI windows nodes are running a windows engine only
There's still one test `TestComposeCancel`  using signals, that needs to be isolated to not compile/run on windows
=> Adapt compose tests to pass with Desktop Windows

cli/cmd/compose/compose.go, go.mod, go.sum
**What I did**
Added support for docker-override files as main compose file sibling when loaded by auto-discovery
close https://github.com/docker/compose-cli/issues/1546
relies on https://github.com/compose-spec/compose-go/pull/131
=> load sibling compose-override file when auto-discovered from parent dir

README.md
**What I did**
* clarify relation to `docker-compose`
* link to #1283 command flag list
Fixes #1473 
=> Update readme and clarify relation to docker-compose

builder.Makefile, cli/cmd/compose/version.go, internal/variables.go, main.go
**What I did**
Separate compose CLI plugin version
https://github.com/docker/dev-tooling-team/issues/285
=> Separate compose CLI plugin version from Cloud integration version

go.mod, go.sum, local/compose/create.go, local/e2e/compose/volumes_test.go
**What I did**
Use `bind` when volume definition require host path to be created when missing, which isn't supported by `mount`
Closes #1543
Supersede #1563
https://docker.atlassian.net/browse/IL-79
=> when bind mount has CreateHostPath set, use bind API

api/compose/api.go, cli/cmd/compose/build.go, local/compose/build.go, local/e2e/compose/compose_build_test.go
**What I did**
Resolve build args without value (`--build-arg FOO`) from environment
close https://github.com/docker/compose-cli/issues/1602
=> resolve build args without value from environment

cli/cmd/compose/version.go
**What I did**
Add missing `\n` to version output
=> cli.compose: Add missing \n for version

local/compose/create.go
**What I did**
detect service dependency involved by `pid: "service:foo`
=> handle dependency involved by shared PID namespace

cli/cmd/compose/remove.go
**What I did**
Add `rm --all` flag (deprecated in docker-compose, just for backward compat ; flag is hidden).
https://github.com/docker/compose-cli/issues/1283
=> Add rm --all flag for backward compatibility (deprecated - no effect)

go.mod, go.sum, local/compose/convergence.go, local/compose/create.go, local/e2e/compose/fixtures/network-alias/compose.yaml, local/e2e/compose/networks_test.go
**What I did**
Fixed networkConfig computation to align with docker-compose
https://github.com/docker/compose/blob/aa45dedb3d5b18df35c5a9c9d54c06cee0cfafe0/compose/service.py#L816
see https://github.com/docker/compose-cli/issues/1620
note: full-fix will require updates in compose-go to introduce service.networks.priority
=> use highest priority network to declare network aliasses

cli/mobycli/exec.go
**What I did**
When not finding com.docker.cli in the PATH, display current path on stderr to help debugging
This adds debug info to help fixing #754 
=> Display PATH when not finding com.docker.cli, to help debugging

local/compose/logs.go
**What I did**
Prevent panic calling r.Close as r is nil
https://github.com/docker/compose-cli/issues/1629
=> don't invoke r.Close on error as r == nil

cli/cmd/compose/compose.go
**What I did**
Only infer implicit profiles to enable when user pass a list of target services, otherwise all service get enabled.
close https://github.com/docker/compose-cli/issues/1636
=> fix detecting active profiles implied by selected services

builder.Makefile
**What I did**
2.0.0-beta.1 => 2.0.0-beta.2
=> Bump compose beta version

go.mod, go.sum, local/e2e/compose/compose_build_test.go
**What I did**
Allow for absolute build context path / Dockerfile path. These path are encountered using ddev, that generates composefiles.
Fixes https://github.com/docker/dev-tooling-team/issues/313
=> Fix building compose files with absolute build context / Dockerfile

aci/context.go, aci/context_test.go, cli/cmd/context/create_aci.go
ACI allow deploying in any location regardless of resource group
**What I did**
Do not always use resource group location, keep user location option if provided
Fixes #1589 
/test-aci
=> Use location specified by user if provided, and do not override with group location

local/compose/convergence.go
**What I did**
Update VSCode and saw this nice warning for a quite common race issue : 
=> Avoid using for variable in go func, as this creates race conditions

local/compose/ps.go, local/compose/ps_test.go
**What I did**
Fix behaviour of `compose ps -a` flag, so that `ps` always list stopped services, and `-a` is used to also include one_off containers (created by run command)
close https://github.com/docker/compose-cli/issues/1552
=> compose ps list stopped containers. -a is used to include oneoff

aci/compose.go, api/client/compose.go, api/compose/api.go, api/compose/delegator.go, api/compose/noimpl.go, cli/cmd/compose/compose.go, cli/cmd/compose/cp.go, cli/metrics/commands.go, ecs/local/compose.go, ecs/up.go, kube/compose.go, local/compose/cp.go, local/e2e/compose/cp_test.go, local/e2e/compose/fixtures/cp-test/cp-folder/cp-me.txt, local/e2e/compose/fixtures/cp-test/cp-me.txt, local/e2e/compose/fixtures/cp-test/docker-compose.yml
**What I did**
Introducing a `docker compose cp` command on local context. It allows you to copy a file/folder between a service container and the local file system the same way `docker cp` does.
If you scaled your service, you can chose which container will receive the file using a `--index=X` as you would when using `docker compose exec`.
I also added a `--all`  flag as a second commit, allowing users to copy to all containers of a service. I added that as a separate commit so it can be discarded easily if we need more time to decide how to tackle this.
https://github.com/docker/compose-cli/issues/1391
=> Add cp command

local/compose/create.go
**What I did**
Allow multiple host ports to be bound to a single container port
close https://github.com/docker/compose-cli/issues/1655
=> support mulitple bindings for same target port

cli/cmd/compose/up.go, local/compose/attach.go
**What I did**
When I remove a service from my compose file, and run `compose up` it still try to attach to a previously defined service:
```
Attaching to nginx_1, foo_1
no such service: nginx
```
This is due to the "create and start" logic, as the later will list containers with project label, and find stopped ones from a previous run, without a matching service definition
=> only start current project services

local/compose/create.go
**What I did**
Used the `Bind` API for named pipes mount, just like we do for bind mounts
close https://github.com/docker/compose-cli/issues/1664
=> named pipe need to be mounted using the bind API

api/compose/api.go, cli/cmd/compose/ps.go, local/compose/ps.go, local/compose/ps_test.go
**What I did**
updated ps output so
- it does not show healthcheck status but for running container
- it includes exit code for exited containers
- it sort ports for predictable output
close https://github.com/docker/compose-cli/issues/1671
close https://github.com/docker/compose-cli/issues/1672
=> ps shows healthcheck only for running container

local/compose/build.go
**What I did**
Resolve build args from environment when running `docker compose up --build`
close https://github.com/docker/compose-cli/issues/1665
=> resolve build args on compose up --build

api/compose/api.go, cli/cmd/compose/restart.go, local/compose/restart.go, local/compose/start.go
**What I did**
Only (re)start selected services when user explicitly pass service names on (re)start commands.
Otherwise consider all project services
close https://github.com/docker/compose-cli/issues/1685
=> only (re)start selected services

.golangci.yml, Dockerfile, aci/convert/convert.go, aci/convert/convert_test.go, aci/convert/ports.go, aci/convert/registry_credentials.go, aci/e2e/aci_secrets_resources/web/main.go, aci/e2e/e2e-aci_test.go, aci/login/login_test.go, cli/cmd/compose/run.go, cli/formatter/colors.go, kube/client/client.go, local/volumes.go
**What I did**
* Mounted the Go cache wherever we mount the module cache
* Bumped golangci-lint 
* Replaced golint with revive based on prompt that golint is deprecated
* Fixed linting errors
=> Bump linter

cli/cmd/compose/build.go, cli/cmd/compose/convert.go, cli/cmd/compose/cp.go, cli/cmd/compose/create.go, cli/cmd/compose/down.go, cli/cmd/compose/exec.go, cli/cmd/compose/port.go, cli/cmd/compose/pull.go, cli/cmd/compose/run.go, cli/cmd/compose/up.go
**What I did**
Moved flags validation/processing into `PreRunE`, so that `RunE` is dedicated to execution.
Longer terms goal is to be able to directly set plain `compose.Service` method as command's `RunE`
=> validate and pre-process flags in PreRun

aci/login/helper.go
When running `docker login azure` on WSL 1, the browser login prompt is not executed, reverting back to the copy-code-from-console-to-this-URL authentication flow. WSL 2 invocations of the same binary work as expected.
The format reported by `/proc/version` differs between versions of WSL; both report the text "Microsoft", albeit in different cases.
WSL 1 Example:
_`Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #488-Microsoft Mon Sep 01 13:43:00 PST 2020`_
WSL 2 Example:
_`Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020`_
Making the `isWsl` check for "microsoft" case-insensitive allows it to work on both WSL versions.
=> Support Azure login page on WSL 1

local/compose/create.go
(eg. /var/run/docker.sock => c:/var/run/docker.sock folder)
**What I did**
test win mount path with ` filepath.IsAbs()`  and also `HasPrefix("/")  for linux abs path...
Fixes https://github.com/docker/compose-cli/issues/1591
=> Do not resolve mount linux abs path as windows path on windows 

local/compose/convergence.go
**What I did**
Prevent a race condition with `container` loop variable running recreate in parallel
maybe will fix https://github.com/docker/compose-cli/issues/1559
=> prevent race condition renaming containers

local/compose/exec.go, local/e2e/compose/compose_exec_test.go
**What I did**
fixed exec environment computation to ignore unset env variable values
close https://github.com/docker/compose-cli/issues/1712
=> remove unresolved vars from env set by `exec`

.github/workflows/ci.yml, .github/workflows/cli-release.yaml, .github/workflows/plugin-release.yaml, Dockerfile, Makefile, README.md, builder.Makefile, cli/cmd/compose/version.go, internal/variables.go, main.go, scripts/install/install_linux.sh, scripts/install/test.Dockerfile
**What I did**
split the release process so `v1.x` will build compose-cli while `v2.x` will build the composev2 cli-plugin. Temporary solution until composev2 code is moved to a new home
see sample release on https://github.com/ndeloof/compose-cli/releases
close https://github.com/docker/compose-cli/issues/1710
internally tracked as https://docker.atlassian.net/browse/IL-159
=> split compose-cli "docker" and composeV2 cli-plugin release processes

api/compose/api.go, api/compose/printer.go, cli/cmd/compose/up.go, cli/cmd/compose/up_test.go, local/compose/attach.go, local/compose/down.go, local/compose/start.go, local/compose/stop_test.go, local/e2e/compose/compose_test.go, local/e2e/compose/fixtures/attach-restart/compose.yaml, utils/hash.go
**What I did**
- Refactored log printer into a reusable component. This will help use the same code for for "logs" command.
- enforce unicity of log presenter by container name to prevent start/attach race conditions
- watch container events to detect containers added by "scale" then attach to collect additional logs on some already running `up --follow` console.
- fixed `scale` so it doesn't re-create containers 
- redesigned event watch so it stops when all project containers are gone.
Bonus:
with redesigned event watch, `TestAttachRestart` fixture doesn't need anymore a fake service to "keep compose running while container is restarting"
internal related issues: 
- https://docker.atlassian.net/browse/IL-105
- https://docker.atlassian.net/browse/IL-201
=> refactor "start" to better handle container restart/new container added by --scale

utils/e2e/framework.go
**What I did**
I have found the tab character in the `fmt.Printf` method and decided that `\t` character will be look cleaner
=> replaced 'tab' to \t character in the Printf

aci/compose.go, api/client/compose.go, api/compose/api.go, api/compose/proxy.go, cli/cmd/compose/build.go, cli/cmd/compose/compose.go, cli/cmd/compose/kill.go, cli/cmd/compose/pause.go, cli/cmd/compose/pull.go, cli/cmd/compose/push.go, cli/cmd/compose/remove.go, cli/cmd/compose/restart.go, cli/cmd/compose/start.go, cli/cmd/compose/stop.go, ecs/local/compose.go, ecs/run.go, kube/compose.go, local/compose/build.go, local/compose/pause.go, local/compose/pull.go, local/compose/push.go, local/compose/remove.go, local/compose/restart.go, local/compose/start.go, local/compose/stop.go
**What I did**
moved `progress.Run` to the backends, to offer more flexibility
(long term plan is to get `Up` implemented by local backend)
=> Move progress writter into backend(s)

local/compose/build.go, local/compose/pull.go, local/e2e/compose/metrics_test.go
**What I did**
Stop using Buildkit hack to get image pulled, first pull then build
TODO investigate how we could get those in parallel within a shared progress.writer
close https://github.com/docker/compose-cli/issues/1732
=> stop using buildkit hack to pull images

cli/mobycli/exec.go, cli/mobycli/exec_unix.go, cli/mobycli/exec_windows.go
Equivalent of https://github.com/docker/cli/commit/fff164c22e8dc904291fecb62307312fd4ca153e
and https://github.com/docker/cli/commit/cedaf44ea2e8b25b5298bac5f432d90033e5ad6a
In go1.14+, SIGURG is used by the runtime to handle preemtable system calls.
In practice this signal is caught *frequently*.
For reference:
https://go.googlesource.com/proposal/+/master/design/24543-non-cooperative-preemption.md
golang/go#37942
**What I did**
=> mobycli: ignore SIGURG on Linux and Darwin

aci/compose.go, cli/cmd/compose/compose.go, cli/cmd/compose/down.go, ecs/down.go, kube/compose.go, local/compose/down.go
**What I did**
Moved progress rendering to backend
Moved check for supported options to backend
this makes `down` CLI command way simpler and independent from backend.
=> move progress to backend on "down"

aci/compose.go, api/compose/api.go, cli/cmd/compose/compose.go, cli/cmd/compose/create.go, cli/cmd/compose/kill.go, cli/cmd/compose/run.go, cli/cmd/compose/up.go, ecs/up.go, kube/compose.go, local/compose/compose.go, local/compose/create.go, local/compose/kill.go, local/compose/kill_test.go, local/compose/start.go, local/compose/up.go
**What I did**
move `up` command logic on backend so that local backend do implement `compose.API#Up`
this removes reference to context type from `cli` package, so that this code is now independent from ACI/ECS/Kube backends
=> move up logic from CLI into local backend

kube/client/client.go, local/compose/attach.go, local/compose/logs.go, utils/logs.go, utils/writer.go, utils/writer_test.go
**What I did**
moved (and renamed) splitWriter into it's own go file
removed reference to container and service names which aren't used anymore.
=> code cleanup: splitWriter does not use service/container name

local/compose/printer.go, local/compose/start.go, local/compose/up.go
**What I did**
Made `logPrinter` private in local backend, not relevant anymore on the API
Made  `watchContainers` more flexible with `onStart` func which is responsible to get just-started container log stream
=> LogPrinter should not be part of the API

cli/cmd/compose/convert.go
**What I did**
updated `config --profiles` so it list all profiles define in compose model
https://github.com/docker/compose-cli/issues/1759
=> config --profiles to list all defined profiles

go.mod, go.sum
see https://github.com/docker/cli/pull/3131
Changes:
- winterm: GetStdFile(): Added compatibility with "golang.org/x/sys/windows"
- winterm: fix GetStdFile() falltrough
- update deprecation message to refer to the correct replacement
full diff:
- https://github.com/moby/term/compare/bea5bbe245bf407372d477f1361d2ff042d2f556...9d4ed185629744f381f269030675cb1957e2da94
- https://github.com/Azure/go-ansiterm/compare/d6e3b3328b783f23731bc4d058875b0371ff8109...2377c96fe7952d1240551745607860c013669458
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
**What I did**
=> go.mod: update moby/term to fix Invalid Standard Handle Panic on Windows

cli/cmd/compose/exec.go, cli/cmd/compose/run.go, local/compose/exec.go, local/e2e/compose/networks_test.go
**What I did**
- Make `compose exec` / `compose run` safer by automatically applying no-TTY option when active shell isn't a terminal
- Fix `compose exec` ran in a non-interactive terminal (see https://docker.atlassian.net/browse/IL-47)
inspired by https://github.com/docker/cli/blob/master/cli/command/container/exec.go
such a pain this code is all private and we can't just use it here.
=> automatically disable TTY if shell isn't a terminal

local/compose/build.go, local/compose/create.go, local/compose/down.go, local/compose/down_test.go
**What I did**
Pass `volume` option to `ContainerRemove` on `compose down` to also drop anonymous volumes
close https://github.com/docker/compose-cli/issues/1755
=> `compose down -v` also removes anonymous volumes

go.mod, go.sum, pkg/api/labels.go, pkg/compose/create.go, pkg/compose/create_test.go
**What I did**
Set compose.version label as `<int>.<int>.<int>` for interoperability with docker-compose (python distutils.LooseVersion)
close https://github.com/docker/compose-cli/issues/1802
=> better interoperability with docker-compose on version label

pkg/compose/convergence.go, pkg/compose/run.go
Compose run is used to execute a "one off" container, restart_policy doesn't make sense in this context (should only apply to long running services)
This also fix incompatibility with auto-remove HostConfig option
Also fix earlier one-off containers being started by `compose up`
close https://github.com/docker/compose-cli/issues/1694
=> Don't apply restart_policy on `compose run`

go.mod, go.sum
follow-up to https://github.com/docker/compose-cli/pull/1774
Fixes an integer overflow when building on 32 bit windows/arm
- https://github.com/moby/term/compare/9d4ed1856297...3f7ff695adc6
- https://github.com/Azure/go-ansiterm/compare/43e1dd70ce54...59db8d763f22
**What I did**
=> go.mod: update moby/term and Azure/go-ansiterm

cmd/compose/compose.go
**What I did**
Introduced `--verbose` command line option to enforce command line compatibility with `docker-compose`.
This just set logging to TRACE level
full compatibility would require to tweak the Docker API client so it dump API calls on console, but AFAIK this is not feasible within a CLI plugin as this would have to apply during client setup.
close https://github.com/docker/compose-cli/issues/1253
=> add --verbose option for compatibility

cmd/compose/ps.go
**What I did**
Added support for `--filter status=xx` and for a cleaner UX introduced preferred flag `--status xx`
_NOTE_ this doesn't support `--filter source=[build|image]` which require the original compose file to know how service is configured (we will need extra labels).
https://github.com/docker/compose-cli/issues/1274
=> implement ps --status=xx filter

.github/workflows/pending_answered.yml
Adds automation to remove issues `pending` label as a new comment is created.
This allows to use this label for issues where we need reporter to provide more details, and exclude them from triage using `-label:pending` as issue search filter.
As user create a new label providing more details, `pending` label will be removed, so this issue will come back under our radar
=> automation to remove pending label on new comment

docs/reference/compose.md
**What I did**
Updated two references to `docker compose` that still said `docker-compose`. See https://github.com/docker/docker.github.io/pull/13015
=> Fix references to docker-compose command

builder.Makefile, scripts/install/install_linux.sh
Signed-off-by: vibhutisawant <Vibhuti.Sawant@ibm.com>
**What I did**
Added support for s390x.
Tested the binary on s390x arch and binary works as expected. Also, all tests have passed successfully.
This PR is related to https://github.com/docker/compose/issues/7785
=> Adds s390x support

.golangci.yml, pkg/compose/attach.go, pkg/compose/exec.go, pkg/compose/run.go
**What I did**
introduced support for detach keys on `compose run` and `compose exec`
close https://github.com/docker/compose-cli/issues/1709
=> add support for detach keys on compose run|exec

pkg/compose/exec.go
**What I did**
close hijacked http stdin stream on EOF to enforce container's exec process to get stdin closed and terminate accordingly.
close https://github.com/docker/compose-cli/issues/1876
=> close sdtin stream on EOF to propagate exec process' stdin

cli/cmd/version.go, cmd/compose/version.go, cmd/main.go
I noticed this when building the binary (see https://github.com/docker/docker-ce-packaging/pull/553); `internal.Version` is set to `v2.0.0-beta.4`, to match the tag.
```bash
GIT_TAG=v2.0.0-beta.4
make COMPOSE_BINARY=bin/docker-compose -f builder.Makefile compose-plugin \
GOOS=linux \
GOARCH=amd64 \
CGO_ENABLED=0 \
go build \
-trimpath \
-ldflags="-s -w -X github.com/docker/compose-cli/internal.Version=v2.0.0-beta.4" \
-o bin/docker-compose \
./cmd
```
However, the binary has the `v` prefix stripped (which caused a check to fail
when packaging):
```bash
/root/rpmbuild/BUILDROOT/docker-compose-plugin-2.0.0.beta.4-0.fc34.x86_64/usr/libexec/docker/cli-plugins/docker-compose docker-cli-plugin-metadata
++ awk '{ gsub(/[",:]/,"")}; $1 == "Version" { print $2 }'
+ ver=2.0.0-beta.4
+ test …
```
=> Do not strip "v" prefix from version when printing

cli/cmd/context/create_kube.go
**What I did**
Small fix to the CLI help text to align with the commands actually being used. Took me a while to figure out why it wasn't working! 😆
=> Fix help text when for context create and kube backend

kube/client/client.go
**What I did**
I'll admit I'm a relatively noob when it comes to Go, but if I had a service with multiple replicas, the log names were always the last pod. Looking at the code, it looks like the variable `pod` is a reference to the next item in the range, which changes each time the range runs. So, the callback in the `utils.GetWriter` references the last pod in the range. I would see output like this (with two nginx replicas running)...
```
app-7fd76968d9-zwmwq  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
app-7fd76968d9-zwmwq  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
app-7fd76968d9-zwmwq  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
app-7fd76968d9-zwmwq  | …
```
=> Fix container name used in kube log output

pkg/compose/convergence.go
**What I did**
`start` command to report error when there's no container to start
close https://github.com/docker/compose-cli/issues/1905
=> report error when there's no container to start

.github/workflows/cli-release.yaml
Signed-off-by: Lorena Rangel <lorena.rangel@docker.com>
**What I did**
Added workflow dispatch to be able to run the release process from GitHub UI. It also has a dry-run check to be able to test the release, without doing an actual release.
closes #349 
=> Add dry run workflow to test release

go.mod, go.sum
**What I did**
Bump compose-go to get fix in https://github.com/compose-spec/compose-go/commit/efad24e892cef59b6f18a303d650455311296b0a
Resolves https://github.com/docker/compose-cli/issues/1892
=> Fix dotEnv load path precedence by compose-go bump

cmd/compose/convert.go
**What I did**
Currently, `compose config --services` outputs the services in
a random/non-deterministic order.
In Compose v1, this was implicitly topologically sorted because
the project services were pre-sorted. With `compose-go`, the
services are unordered, and the `WithServices()` helper can be
used to iterate in dependency order.
**Tests**
There wasn't a great way to unit test this without further refactoring
as `runServices` uses `convertOptions::toProject()` which will
attempt to load a real Compose file. (AFAICT there aren't really any
existing CLI unit tests.)
If desirable, I can split the function in two so that the project
conversion from opts is separate from the actual logic which can
just take a `*types.Project` and so would be trivially testable.
**(not mandatory) A picture …
=> Print services in dependency order

pkg/compose/attach.go, pkg/compose/exec.go, pkg/compose/run.go
**What I did**
Restore support for control sequence in `compose run`
close https://github.com/docker/compose-cli/issues/1908
=> Restore support for control sequence in `compose run`

pkg/compose/convergence.go
**What I did**
Add check for 0 length containers list, and remove explicit error return for no running services (this is expected).
I'm not familiar enough with the internals of this program to know what far-reaching consequences changing `updateProject` and `startService` in this way will have, but I hope the automated tests in CI will catch anything untoward.
fixes #1909
=> allow for 0 scale/replicas

cli/mobycli/pat_suggest.go
**What I did**
Update PAT (personal access token) post-login message to use a stable URL
=> Update personal access token url

cli/mobycli/pat_suggest.go, cli/mobycli/pat_suggest_test.go
Signed-off-by: Amine Chouki <amine.chouki@docker.com>
**What I did**
Do not display the post-login message (to promote Personal Access Tokens) if the password is empty. This is more of a future proof check in case we introduce SSO or equivalent.
=> Post-login msg: Ignore if password is empty

kube/resources/kube.go
The Compose spec doesn't provide a default value, but the code
was defaulting to TCP in the service protocol, just not in the
name. If no protocol was specified, it would cause an invalid
service name (eg, "80-")
**What I did**
I updated the service name to use the same `toProtocol` function to remove the option for an invalid service name.
=> Allow unspecified protocol on exposed port in kube backend

cmd/compose/remove.go, pkg/e2e/compose_test.go
**What I did**
When `docker compose rm` is run with `-s` (`--stop`), it actually does not remove containers, just stops them.
This PR fixes this issue.
=> Fix issue `docker compose rm -s` not removing containers

pkg/compose/create.go
**What I did**
added support for `expose` config as we compute container ports
close https://github.com/docker/compose-cli/issues/1950
=> include exposed ports in container ports config

CONTRIBUTING.md
**What I did**
I'm getting the `NET::ERR_CERT_COMMON_NAME_INVALID` error when accessing the link to Docker Community Slack.
So I fixed the link.
=> Fix slack link

pkg/compose/events.go
**What I did**
Filter-out one-off container watching events. This prevents `up` to consider a one-off container to be part of the app and attach to it, then exit when container stops
close https://github.com/docker/compose-cli/issues/1955
=> ignore one-off container events

.github/ISSUE_TEMPLATE.md
1. There was a trailing asterisk in one of the headers, preventing the formatting from being applied.
2. There needs to be a blank line between the bold header and the code block in order for formatting to be applied to the header.
**What I did**
Fixed formatting bug in ISSUE_TEMPLATE.md
N/A
```
/\/\/\o
```
=> Fix formatting bug in ISSUE_TEMPLATE.md

pkg/api/labels.go, pkg/compose/build.go
**What I did**
don't override service.image with local digest, better use a new label to track the image used to create service, and detect service need to be re-created after image has been re-built
fix https://github.com/docker/compose-cli/issues/1983
=> introduce ImageDigestLabel to track image built for service

pkg/api/labels.go, pkg/compose/build.go
Reverts docker/compose-cli#1997 as it wasn’t actually passing CI.
=> Revert "introduce ImageDigestLabel to track image built for service"

pkg/compose/down.go, pkg/compose/down_test.go, pkg/compose/kill_test.go, pkg/compose/ps_test.go, pkg/compose/stop_test.go, pkg/e2e/compose_test.go
**What I did**
Use strings.ToLower(projectName)
Resolves https://github.com/docker/compose-cli/issues/2023
=> Lowercase project name for "compose down"

go.mod, go.sum
**What I did**
Bump `compose-spec/compose-go`
Resolves https://github.com/docker/compose-cli/issues/2013 
Resolves https://github.com/docker/compose-cli/issues/2014
Resolves https://github.com/docker/compose-cli/issues/2018
Resolves https://github.com/docker/compose-cli/issues/2036
Resolves https://github.com/docker/compose-cli/issues/2022
Still needs the merge on `compose-spec/compose-go`
=> Bump compose-go

pkg/compose/run.go
**What I did**
invoke `prepareVolumes` on service targetted by `run` 
as the global prepare logic is only applied to dependencies by the `run` execution flow
close https://github.com/docker/compose-cli/issues/2021
=> prepare volume for service set by `run`

BUILDING.md
**What I did**
minor updates to ACI token generation and renewal for CI
=> Update doc for ACI token renewal

pkg/compose/create.go
**What I did**
added support for XXX_PROXY env variables based on docker config file
https://github.com/docker/compose-cli/issues/2032
=> set proxy env vars based on CLI config

pkg/compose/run.go
`prepareVolumes` MUST be ran _before_ we retrieve a `ServiceConfig` reference otherwise the copy we get isn't up-to-date with `volumes_from` set to actual container
#fix https://github.com/docker/compose-cli/issues/2035
also require https://github.com/compose-spec/compose-go/pull/177
=> update project's volumes_from before retrieving service

cmd/compose/ps.go, pkg/compose/run.go, pkg/e2e/compose_run_test.go
Don't exit with code != 0 when we succeed listing container but just none match compose project
Also includes a fix to e2e test flackyness
close https://github.com/docker/compose-cli/issues/2057
=> Don't exit with code != 0 on `compose ps` empty result

.github/workflows/cli-release.yaml
**What I did**
fixed release workflow, to procude binary with GIT_TAG as internal.version
=> fix release project to build with GIT_TAG

README.md
**What I did**
Document Compose V2 code has moved to github.com/docker/compose
=> redirect compose v2 users to github.com/docker/compose

kube/client/client.go
**What I did**
This PR provides the ability to perform a `docker compose exec <pod-name|service-name>` in the kube context and serves as an implementation of #1920. It looks at the requested name to see if it matches a pod name and exec's to it if a match is found. Otherwise, it falls back to the current implementation where it finds a matching pod by service.
The big reason to do this is to allow teams to stay within the compose tooling and exec into specific instances. In a normal Docker context, a user can simply use `docker exec`. But, that doesn't work in a kube context. They can look at logs to potentially find a problem, but have to switch to another tool to exec to the specific instance they want. And having to switch to `kubectl` and making sure you're in the right …
=> Allow compose exec to accept a specific instance in kube backend

go.mod, go.sum
**What I did**
Bump compose v2
=> Bump compose to v2.1.0

cli/main.go
**What I did**
This makes the distinction between version command in "docker version" and "docker compose version"
In the second case it needs to delegate to the plugin.
Maybe another approach would be better. For example, with the full command chain as command identifier.
I just don't know if that's worth for now... Cases like this should remain very rare.
=> Fix plugin command delegation for version

cli/cmd/context/context.go, cli/cmd/context/create.go, cli/cmd/context/ls.go, cli/cmd/context/update.go, cli/cmd/login/login.go, cli/cmd/version.go, cli/main.go, cli/mobycli/exec.go, cli/mobycli/exec_unix.go, cli/mobycli/exec_windows.go
Reverts docker/compose-cli#1879
Reverting as it’s breaking some integration tests downstream.
We’ll take another look later.
@ndeloof FIY ☝️
=> Revert "signals"

ecs/compatibility.go, ecs/convert.go
**What I did**
I added support for passing docker labels into the provided ECS DockerLabels in cloud-formation.
closes #2110
=> [ECS] Add support for passing in docker labels.

ecs/autoscaling_test.go, ecs/cloudformation.go, ecs/cloudformation_test.go, ecs/ec2_test.go
**What I did**
I implemented a solution to check if a docker compose volume is with `source` field valid to avoid a panic on ec2 template creation.
Use `docker compose up` with a 'wrong' compose file like this:
```
services:
my-mongo:
image: mongo
volumes:
- mongodata # here is the panic cause
volumes:
mongodata:
```
Generates a panic:
```
goroutine 39 [running]:
github.com/docker/compose-cli/ecs.(*ecsAPIService).createTaskRole(0xc000400540, 0xc0009b6e60, 0xc000556240, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3dd7288, ...)
github.com/docker/compose-cli/ecs/cloudformation.go:465 +0x34a
github.com/docker/compose-cli/ecs.(*ecsAPIService).createService(0xc000400540, 0xc0009b6e60, 0xc000556240, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3dd7288, ...) …
```
=> fix: panic with ec2 source less volumes

api/context/store/store.go
**What I did**
Removed the call to com.docker.cli to get the default context that was [added here](https://github.com/docker/compose-cli/pull/401). This is no longer needed since the `docker compose` command was moved to a cli plugin for moby contexts
=> Remove the call to com.docker.cli to get the default context

ecs/logs.go
**What I did**
Fix default behaviour for ecs flag `--tail`  in log command
Resolves https://github.com/docker/compose/issues/9126
=> Fix default behaviour for ecs flag `--tail` in log command

cli/metrics/metadata/build.go
**What I did**
Got a hard time to pinpoint this issue but finally found it comes from the cli proxy while parsing args with pflags for build metrics:
```
$ docker buildx inspect --help
Usage:  docker buildx inspect [NAME]
Inspect current builder instance
Options:
--bootstrap        Ensure builder has booted before inspecting
--builder string   Override the configured builder instance
Usage of buildx:
--builder string
```
Now with flag set usage silenced:
```
$ docker buildx inspect --help
Usage:  docker buildx inspect [NAME]
Inspect current builder instance
Options:
--bootstrap        Ensure builder has booted before inspecting
--builder string   Override the configured builder instance
```
cc @tonistiigi
* https://github.com/docker/buildx/issues/990
Signed-off-by: …
=> metrics: fix unexpected usage output shown on cli

cli/cmd/version_test.go, cli/mobycli/pat_suggest_test.go, go.mod, go.sum
**What I did**
Update `gotest.tools` to a version which support golang `1.18.x`
=> update gotest.tools to v3.3.0 which support golang 1.18

cli/mobycli/exec.go, cli/mobycli/exec_test.go
**What I did**
Update the way we choose which `com.docker.cli` binary executable to use.
1. Use path from env variable `$DOCKER_COM_DOCKER_CLI` if defined and non-empty
2. Use path formed from parent directory of current process executable joined with
`com.docker.cli`
3. Look for `com.docker.cli` on $PATH
=> cli binary path handling

aci/login/login.go, kube/client/client.go, kube/helm/chart.go, kube/resources/kube.go, utils/e2e/framework.go
Prepare for future updates of Go, which may result in some changes in
formatting in GoDoc comments.
**What I did**
Ran `gofmt -s -w .` with go 1.19rc2
=> gofmt files with go 1.19

Makefile
**What I did**
Updated `Makefile` to use `docker buildx` to build the ECS sidecar images for both AMD64 and ARM64.
ECS Fargate supports both AMD64 and ARM64.  Running `docker --context ecs compose up` introduces sidecar images which are only built for AMD64.  This results in all deployments to ARM64 failing. Publishing ARM64 images would fix issue #2190 and #2115.
=> Added Linux/ARM64 to ECS sidecar builds fixes #2190 and #2115

docs/aci-container-features.md
**What I did**
I applied a wording fix to `docs/aci-container-features.md` suggested in #2154, wherein the sentence:
> A single container is executed in its own ACI container group, that will container only one container.
becomes:
> A single container is executed in its own ACI container group, which will contain a single container.
closes #2154
=> docs: applies wording suggested in #2154

cli/metrics/commands.go
**What I did**
Update metrics whitelist to get analytics on `docker extension share` 
Note that I did run `generatecommands/main.go, but it gave me a bunch of other changes in addition to the share command, I didn't want to include things I'm not sure about so I prefer to keep this PR short and easy to merge
=> Add share command (docker extension share) in metrics whitelist

cli/main.go, cli/metrics/client.go, cli/metrics/event.go, cli/metrics/metrics.go, cli/mobycli/exec.go, cli/server/metrics.go, cli/server/metrics_test.go
Compose doesn't actually currently use this code, it's only used here. Moving it inline so that we can drop it from Compose in the future or make changes as needed without worrying about this as a dependency.
=> metrics: move helper code from Compose

cli/main.go, cli/metrics/client.go, cli/metrics/event.go, cli/metrics/metrics.go, cli/mobycli/exec.go, cli/server/metrics.go, cli/server/metrics_test.go
Add a timer around command invocations to be reported with metrics.
This isn't actually sent anywhere currently, as it's meant for
evented data which is forthcoming. (We could report it with the
current events, but it's not clear that there's any value in doing
so.)
The signature for `Track()` has been changed to take an object with
all the fields. This is both for sanity to keep the method from
getting ridiculously long, and to make it easier to unify the usage
(heartbeat) and event code paths by ensuring we have all the data
for both.
(Replaces #2224 which I accidentally closed and can't re-open 😅)
=> metrics: initial logic for command execution duration

README.md, aci/backend.go, aci/cloud.go, ecs/backend.go
https://docker.atlassian.net/browse/ENV-189
**What I did**
added a deprecation notice when compose-cli is used with a non-default context type
```
$ docker context create ecs toto
Cloud integration is DEPRECATED. Read more on https://docs.docker.com/cloud/ecs-integration/
? Create a Docker context using:  [Use arrows to move, type to filter]
..
```
=> cli: deprecation notice

aci/backend.go, aci/cloud.go, ecs/backend.go, utils/deprecation.go
**What I did**
Added `COMPOSE_CLOUD_EOL_SILENT` env var, which will suppress the EOL message if set to a truthy value.
#2245
=> cli: allow suppressing deprecation warning

cli/mobycli/pat_suggest.go, cli/mobycli/pat_suggest_test.go
**What I did**
When logging in with a PAT, `docker login` tells me... I should be using a PAT:
```
docker login
Authenticating with existing credentials...
Login Succeeded
Logging in with your password grants your terminal complete access to your account.
For better security, log in with a limited-privilege personal access token. Learn more at https://docs.docker.com/go/access-tokens/
```
compose-cli is looking for the prefix `dckrp_` but hub currently issues pats with the prefix `dckr_pat_`.
Also check for the prefix `dckr_pat_`. (maybe we could just exclusively check for this prefix? I have not looked into the history of `dckrp_`)
=> compose-cli: fix PAT detection for PAT suggestion

cli/mobycli/exec.go, cli/mobycli/pat_suggest.go
**What I did**
Removed the PAT message, we are moving this to docker/cli https://github.com/docker/cli/pull/4478
=> login: Remove the PAT message
